package com.moji.keyboard

data class EmojiItem(
    val id: String,
    val emoji: String,
    val name: String,
    val category: EmojiCategory,
    val keywords: List<String>,
    val hasSkinTones: Boolean = false,
    val skinToneVariants: List<String> = emptyList()
)

enum class EmojiCategory(val label: String, val icon: String) {
    RECENT("Recent", "🕐"),
    SMILEYS("Smileys", "😀"),
    PEOPLE("People", "👋"),
    NATURE("Nature", "🌸"),
    FOOD("Food", "🍎"),
    TRAVEL("Travel", "✈️"),
    ACTIVITIES("Activities", "⚽"),
    OBJECTS("Objects", "💡"),
    SYMBOLS("Symbols", "❤️"),
    MEDIEVAL("Medieval & Fantasy", "⚔️"),
    HERB("420", "🌿"),
    SCIFI("Sci-Fi", "🛸"),
    HORROR("Horror", "💀"),
    MUSIC("Music", "🎵"),
    OCEAN("Ocean", "🌊")
}

object EmojiDatabase {
    private fun skinTones(base: String) = listOf(
        "$base🏻", "$base🏼", "$base🏽",
        "$base🏾", "$base🏿"
    )

    val all: List<EmojiItem> = listOf(
        // Smileys
        EmojiItem("grinning", "😀", "Grinning Face", EmojiCategory.SMILEYS, listOf("smile","happy","face")),
        EmojiItem("joy", "😂", "Face with Tears of Joy", EmojiCategory.SMILEYS, listOf("laugh","happy","cry")),
        EmojiItem("rofl", "🤣", "Rolling on Floor Laughing", EmojiCategory.SMILEYS, listOf("laugh","funny")),
        EmojiItem("smile", "😊", "Smiling Face", EmojiCategory.SMILEYS, listOf("smile","happy")),
        EmojiItem("wink", "😉", "Winking Face", EmojiCategory.SMILEYS, listOf("wink","smile")),
        EmojiItem("heart_eyes", "😍", "Heart Eyes", EmojiCategory.SMILEYS, listOf("love","heart")),
        EmojiItem("star_eyes", "🤩", "Star Eyes", EmojiCategory.SMILEYS, listOf("star","excited")),
        EmojiItem("kiss", "😘", "Kissing Heart", EmojiCategory.SMILEYS, listOf("kiss","love")),
        EmojiItem("thinking", "🤔", "Thinking Face", EmojiCategory.SMILEYS, listOf("think","hmm")),
        EmojiItem("flushed", "😳", "Flushed Face", EmojiCategory.SMILEYS, listOf("blush","shy")),
        EmojiItem("sob", "😭", "Loudly Crying", EmojiCategory.SMILEYS, listOf("cry","sad")),
        EmojiItem("angry", "😠", "Angry Face", EmojiCategory.SMILEYS, listOf("angry","mad")),
        EmojiItem("rage", "😡", "Pouting Face", EmojiCategory.SMILEYS, listOf("angry","rage")),
        EmojiItem("skull", "💀", "Skull", EmojiCategory.SMILEYS, listOf("dead","skull")),
        EmojiItem("ghost", "👻", "Ghost", EmojiCategory.SMILEYS, listOf("ghost","boo")),
        EmojiItem("alien", "👽", "Alien", EmojiCategory.SMILEYS, listOf("alien","space")),
        EmojiItem("fire_eyes", "🤬", "Face with Symbols", EmojiCategory.SMILEYS, listOf("angry","censored")),
        EmojiItem("hot", "🥵", "Hot Face", EmojiCategory.SMILEYS, listOf("hot","warm")),
        EmojiItem("cold", "🥶", "Cold Face", EmojiCategory.SMILEYS, listOf("cold","freezing")),
        EmojiItem("sleeping", "😴", "Sleeping", EmojiCategory.SMILEYS, listOf("sleep","tired")),
        EmojiItem("sick", "🤒", "Sick Face", EmojiCategory.SMILEYS, listOf("sick","ill")),
        EmojiItem("mask", "😷", "Medical Mask", EmojiCategory.SMILEYS, listOf("sick","mask")),
        EmojiItem("cowboy", "🤠", "Cowboy Hat", EmojiCategory.SMILEYS, listOf("cowboy","hat")),
        EmojiItem("partying", "🥳", "Partying Face", EmojiCategory.SMILEYS, listOf("party","celebrate")),
        EmojiItem("monocle", "🧐", "Monocle Face", EmojiCategory.SMILEYS, listOf("monocle","fancy")),
        EmojiItem("nerd", "🤓", "Nerd Face", EmojiCategory.SMILEYS, listOf("nerd","glasses")),
        EmojiItem("sunglasses", "😎", "Sunglasses", EmojiCategory.SMILEYS, listOf("cool","sunglasses")),
        EmojiItem("clown", "🤡", "Clown Face", EmojiCategory.SMILEYS, listOf("clown","joker")),
        EmojiItem("poop", "💩", "Pile of Poo", EmojiCategory.SMILEYS, listOf("poop","funny")),
        EmojiItem("rainbow_flag", "🏳️‍🌈", "Rainbow Flag", EmojiCategory.SMILEYS, listOf("pride","rainbow")),

        // People
        EmojiItem("wave", "👋", "Waving Hand", EmojiCategory.PEOPLE, listOf("wave","hello"), true, skinTones("👋")),
        EmojiItem("thumbsup", "👍", "Thumbs Up", EmojiCategory.PEOPLE, listOf("thumbs","good"), true, skinTones("👍")),
        EmojiItem("thumbsdown", "👎", "Thumbs Down", EmojiCategory.PEOPLE, listOf("thumbs","bad"), true, skinTones("👎")),
        EmojiItem("clap", "👏", "Clapping Hands", EmojiCategory.PEOPLE, listOf("clap","applause"), true, skinTones("👏")),
        EmojiItem("raised_hands", "🙌", "Raising Hands", EmojiCategory.PEOPLE, listOf("celebrate","party"), true, skinTones("🙌")),
        EmojiItem("fist", "✊", "Raised Fist", EmojiCategory.PEOPLE, listOf("fist","power"), true, skinTones("✊")),
        EmojiItem("punch", "👊", "Oncoming Fist", EmojiCategory.PEOPLE, listOf("punch","hit"), true, skinTones("👊")),
        EmojiItem("ok_hand", "👌", "OK Hand", EmojiCategory.PEOPLE, listOf("ok","good"), true, skinTones("👌")),
        EmojiItem("peace", "✌️", "Victory Hand", EmojiCategory.PEOPLE, listOf("peace","victory"), true, skinTones("✌️")),
        EmojiItem("love_you", "🤟", "Love You Gesture", EmojiCategory.PEOPLE, listOf("love","rock"), true, skinTones("🤟")),
        EmojiItem("metal", "🤘", "Sign of Horns", EmojiCategory.PEOPLE, listOf("rock","metal"), true, skinTones("🤘")),
        EmojiItem("call_me", "🤙", "Call Me Hand", EmojiCategory.PEOPLE, listOf("call","phone"), true, skinTones("🤙")),
        EmojiItem("point_right", "👉", "Pointing Right", EmojiCategory.PEOPLE, listOf("point","right"), true, skinTones("👉")),
        EmojiItem("point_left", "👈", "Pointing Left", EmojiCategory.PEOPLE, listOf("point","left"), true, skinTones("👈")),
        EmojiItem("point_up", "☝️", "Pointing Up", EmojiCategory.PEOPLE, listOf("point","up"), true, skinTones("☝️")),
        EmojiItem("point_down", "👇", "Pointing Down", EmojiCategory.PEOPLE, listOf("point","down"), true, skinTones("👇")),
        EmojiItem("raised_hand", "✋", "Raised Hand", EmojiCategory.PEOPLE, listOf("hand","stop"), true, skinTones("✋")),
        EmojiItem("vulcan", "🖖", "Vulcan Salute", EmojiCategory.PEOPLE, listOf("spock","peace"), true, skinTones("🖖")),
        EmojiItem("handshake", "🤝", "Handshake", EmojiCategory.PEOPLE, listOf("deal","handshake")),
        EmojiItem("pray", "🙏", "Folded Hands", EmojiCategory.PEOPLE, listOf("pray","thanks"), true, skinTones("🙏")),
        EmojiItem("muscle", "💪", "Flexed Biceps", EmojiCategory.PEOPLE, listOf("strong","muscle"), true, skinTones("💪")),
        EmojiItem("nail_polish", "💅", "Nail Polish", EmojiCategory.PEOPLE, listOf("nails","beauty"), true, skinTones("💅")),
        EmojiItem("ear", "👂", "Ear", EmojiCategory.PEOPLE, listOf("ear","listen"), true, skinTones("👂")),
        EmojiItem("nose", "👃", "Nose", EmojiCategory.PEOPLE, listOf("nose","smell"), true, skinTones("👃")),
        EmojiItem("eyes", "👀", "Eyes", EmojiCategory.PEOPLE, listOf("eyes","look")),
        EmojiItem("brain", "🧠", "Brain", EmojiCategory.PEOPLE, listOf("brain","smart")),
        EmojiItem("heart_organ", "🫀", "Anatomical Heart", EmojiCategory.PEOPLE, listOf("heart","organ")),
        EmojiItem("lungs", "🫁", "Lungs", EmojiCategory.PEOPLE, listOf("lungs","breath")),
        EmojiItem("baby", "👶", "Baby", EmojiCategory.PEOPLE, listOf("baby","child"), true, skinTones("👶")),
        EmojiItem("boy", "👦", "Boy", EmojiCategory.PEOPLE, listOf("boy","child"), true, skinTones("👦")),
        EmojiItem("girl", "👧", "Girl", EmojiCategory.PEOPLE, listOf("girl","child"), true, skinTones("👧")),

        // Nature
        EmojiItem("dog", "🐶", "Dog Face", EmojiCategory.NATURE, listOf("dog","pet")),
        EmojiItem("cat", "🐱", "Cat Face", EmojiCategory.NATURE, listOf("cat","pet")),
        EmojiItem("mouse", "🐭", "Mouse Face", EmojiCategory.NATURE, listOf("mouse","animal")),
        EmojiItem("hamster", "🐹", "Hamster", EmojiCategory.NATURE, listOf("hamster","cute")),
        EmojiItem("rabbit", "🐰", "Rabbit Face", EmojiCategory.NATURE, listOf("rabbit","bunny")),
        EmojiItem("fox", "🦊", "Fox", EmojiCategory.NATURE, listOf("fox","animal")),
        EmojiItem("bear", "🐻", "Bear Face", EmojiCategory.NATURE, listOf("bear","animal")),
        EmojiItem("panda", "🐼", "Panda", EmojiCategory.NATURE, listOf("panda","cute")),
        EmojiItem("koala", "🐨", "Koala", EmojiCategory.NATURE, listOf("koala","australia")),
        EmojiItem("tiger", "🐯", "Tiger Face", EmojiCategory.NATURE, listOf("tiger","animal")),
        EmojiItem("lion", "🦁", "Lion", EmojiCategory.NATURE, listOf("lion","king")),
        EmojiItem("cow", "🐮", "Cow Face", EmojiCategory.NATURE, listOf("cow","animal")),
        EmojiItem("pig", "🐷", "Pig Face", EmojiCategory.NATURE, listOf("pig","oink")),
        EmojiItem("frog", "🐸", "Frog", EmojiCategory.NATURE, listOf("frog","green")),
        EmojiItem("monkey", "🐵", "Monkey Face", EmojiCategory.NATURE, listOf("monkey","ape")),
        EmojiItem("chicken", "🐔", "Chicken", EmojiCategory.NATURE, listOf("chicken","bird")),
        EmojiItem("penguin", "🐧", "Penguin", EmojiCategory.NATURE, listOf("penguin","bird")),
        EmojiItem("bird", "🐦", "Bird", EmojiCategory.NATURE, listOf("bird","fly")),
        EmojiItem("owl", "🦉", "Owl", EmojiCategory.NATURE, listOf("owl","wise")),
        EmojiItem("butterfly", "🦋", "Butterfly", EmojiCategory.NATURE, listOf("butterfly","insect")),
        EmojiItem("flower", "🌸", "Cherry Blossom", EmojiCategory.NATURE, listOf("flower","pink")),
        EmojiItem("rose", "🌹", "Rose", EmojiCategory.NATURE, listOf("rose","love")),
        EmojiItem("sunflower", "🌻", "Sunflower", EmojiCategory.NATURE, listOf("sunflower","flower")),
        EmojiItem("tree", "🌳", "Deciduous Tree", EmojiCategory.NATURE, listOf("tree","nature")),
        EmojiItem("palm", "🌴", "Palm Tree", EmojiCategory.NATURE, listOf("palm","beach")),
        EmojiItem("cactus", "🌵", "Cactus", EmojiCategory.NATURE, listOf("cactus","desert")),
        EmojiItem("mushroom", "🍄", "Mushroom", EmojiCategory.NATURE, listOf("mushroom","fungi")),
        EmojiItem("earth", "🌍", "Earth Globe", EmojiCategory.NATURE, listOf("earth","world")),
        EmojiItem("sun", "☀️", "Sun", EmojiCategory.NATURE, listOf("sun","bright")),
        EmojiItem("moon", "🌙", "Crescent Moon", EmojiCategory.NATURE, listOf("moon","night")),

        // Food
        EmojiItem("apple", "🍎", "Red Apple", EmojiCategory.FOOD, listOf("apple","fruit")),
        EmojiItem("banana", "🍌", "Banana", EmojiCategory.FOOD, listOf("banana","fruit")),
        EmojiItem("grapes", "🍇", "Grapes", EmojiCategory.FOOD, listOf("grapes","fruit")),
        EmojiItem("strawberry", "🍓", "Strawberry", EmojiCategory.FOOD, listOf("strawberry","berry")),
        EmojiItem("watermelon", "🍉", "Watermelon", EmojiCategory.FOOD, listOf("watermelon","summer")),
        EmojiItem("lemon", "🍋", "Lemon", EmojiCategory.FOOD, listOf("lemon","sour")),
        EmojiItem("pizza", "🍕", "Pizza", EmojiCategory.FOOD, listOf("pizza","food")),
        EmojiItem("burger", "🍔", "Hamburger", EmojiCategory.FOOD, listOf("burger","food")),
        EmojiItem("fries", "🍟", "French Fries", EmojiCategory.FOOD, listOf("fries","food")),
        EmojiItem("hotdog", "🌭", "Hot Dog", EmojiCategory.FOOD, listOf("hotdog","sausage")),
        EmojiItem("taco", "🌮", "Taco", EmojiCategory.FOOD, listOf("taco","mexican")),
        EmojiItem("burrito", "🌯", "Burrito", EmojiCategory.FOOD, listOf("burrito","wrap")),
        EmojiItem("sushi", "🍣", "Sushi", EmojiCategory.FOOD, listOf("sushi","japanese")),
        EmojiItem("ramen", "🍜", "Ramen", EmojiCategory.FOOD, listOf("ramen","noodles")),
        EmojiItem("cake", "🎂", "Birthday Cake", EmojiCategory.FOOD, listOf("cake","birthday")),
        EmojiItem("ice_cream", "🍦", "Ice Cream", EmojiCategory.FOOD, listOf("ice cream","sweet")),
        EmojiItem("donut", "🍩", "Donut", EmojiCategory.FOOD, listOf("donut","sweet")),
        EmojiItem("cookie", "🍪", "Cookie", EmojiCategory.FOOD, listOf("cookie","sweet")),
        EmojiItem("coffee", "☕", "Hot Beverage", EmojiCategory.FOOD, listOf("coffee","tea")),
        EmojiItem("beer", "🍺", "Beer Mug", EmojiCategory.FOOD, listOf("beer","drink")),
        EmojiItem("wine", "🍷", "Wine Glass", EmojiCategory.FOOD, listOf("wine","drink")),
        EmojiItem("cocktail", "🍹", "Tropical Drink", EmojiCategory.FOOD, listOf("cocktail","drink")),
        EmojiItem("bubble_tea", "🧋", "Bubble Tea", EmojiCategory.FOOD, listOf("boba","tea")),

        // Travel
        EmojiItem("airplane", "✈️", "Airplane", EmojiCategory.TRAVEL, listOf("fly","travel")),
        EmojiItem("rocket", "🚀", "Rocket", EmojiCategory.TRAVEL, listOf("rocket","space")),
        EmojiItem("car", "🚗", "Automobile", EmojiCategory.TRAVEL, listOf("car","drive")),
        EmojiItem("bus", "🚌", "Bus", EmojiCategory.TRAVEL, listOf("bus","transit")),
        EmojiItem("train", "🚂", "Train", EmojiCategory.TRAVEL, listOf("train","rail")),
        EmojiItem("ship", "🚢", "Ship", EmojiCategory.TRAVEL, listOf("ship","boat")),
        EmojiItem("bicycle", "🚲", "Bicycle", EmojiCategory.TRAVEL, listOf("bike","cycle")),
        EmojiItem("house", "🏠", "House", EmojiCategory.TRAVEL, listOf("home","house")),
        EmojiItem("building", "🏢", "Office Building", EmojiCategory.TRAVEL, listOf("office","building")),
        EmojiItem("hospital", "🏥", "Hospital", EmojiCategory.TRAVEL, listOf("hospital","medical")),
        EmojiItem("school", "🏫", "School", EmojiCategory.TRAVEL, listOf("school","education")),
        EmojiItem("beach", "🏖️", "Beach", EmojiCategory.TRAVEL, listOf("beach","sand")),
        EmojiItem("mountain", "⛰️", "Mountain", EmojiCategory.TRAVEL, listOf("mountain","hike")),
        EmojiItem("rainbow", "🌈", "Rainbow", EmojiCategory.TRAVEL, listOf("rainbow","colorful")),
        EmojiItem("camping", "🏕️", "Camping", EmojiCategory.TRAVEL, listOf("camp","tent")),

        // Activities
        EmojiItem("soccer", "⚽", "Soccer Ball", EmojiCategory.ACTIVITIES, listOf("soccer","sports")),
        EmojiItem("basketball", "🏀", "Basketball", EmojiCategory.ACTIVITIES, listOf("basketball","sports")),
        EmojiItem("football", "🏈", "Football", EmojiCategory.ACTIVITIES, listOf("football","sports")),
        EmojiItem("baseball", "⚾", "Baseball", EmojiCategory.ACTIVITIES, listOf("baseball","sports")),
        EmojiItem("tennis", "🎾", "Tennis", EmojiCategory.ACTIVITIES, listOf("tennis","sports")),
        EmojiItem("volleyball", "🏐", "Volleyball", EmojiCategory.ACTIVITIES, listOf("volleyball","sports")),
        EmojiItem("bowling", "🎳", "Bowling", EmojiCategory.ACTIVITIES, listOf("bowling","sports")),
        EmojiItem("golf", "⛳", "Golf", EmojiCategory.ACTIVITIES, listOf("golf","sports")),
        EmojiItem("gaming", "🎮", "Video Game", EmojiCategory.ACTIVITIES, listOf("game","gaming")),
        EmojiItem("guitar", "🎸", "Guitar", EmojiCategory.ACTIVITIES, listOf("guitar","music")),
        EmojiItem("music", "🎵", "Musical Note", EmojiCategory.ACTIVITIES, listOf("music","note")),
        EmojiItem("mic", "🎤", "Microphone", EmojiCategory.ACTIVITIES, listOf("mic","sing")),
        EmojiItem("art", "🎨", "Artist Palette", EmojiCategory.ACTIVITIES, listOf("art","paint")),
        EmojiItem("movie", "🎬", "Clapperboard", EmojiCategory.ACTIVITIES, listOf("movie","film")),
        EmojiItem("trophy", "🏆", "Trophy", EmojiCategory.ACTIVITIES, listOf("trophy","win")),

        // Objects
        EmojiItem("phone", "📱", "Mobile Phone", EmojiCategory.OBJECTS, listOf("phone","mobile")),
        EmojiItem("laptop", "💻", "Laptop", EmojiCategory.OBJECTS, listOf("laptop","computer")),
        EmojiItem("camera", "📷", "Camera", EmojiCategory.OBJECTS, listOf("camera","photo")),
        EmojiItem("tv", "📺", "Television", EmojiCategory.OBJECTS, listOf("tv","screen")),
        EmojiItem("headphones", "🎧", "Headphones", EmojiCategory.OBJECTS, listOf("headphones","music")),
        EmojiItem("bulb", "💡", "Light Bulb", EmojiCategory.OBJECTS, listOf("idea","light")),
        EmojiItem("book", "📖", "Open Book", EmojiCategory.OBJECTS, listOf("book","read")),
        EmojiItem("money", "💰", "Money Bag", EmojiCategory.OBJECTS, listOf("money","rich")),
        EmojiItem("gift", "🎁", "Gift", EmojiCategory.OBJECTS, listOf("gift","present")),
        EmojiItem("key", "🔑", "Key", EmojiCategory.OBJECTS, listOf("key","lock")),
        EmojiItem("lock", "🔒", "Locked", EmojiCategory.OBJECTS, listOf("lock","secure")),
        EmojiItem("hammer", "🔨", "Hammer", EmojiCategory.OBJECTS, listOf("hammer","tool")),
        EmojiItem("pill", "💊", "Pill", EmojiCategory.OBJECTS, listOf("pill","medicine")),
        EmojiItem("scissors", "✂️", "Scissors", EmojiCategory.OBJECTS, listOf("cut","scissors")),

        // Symbols
        EmojiItem("heart", "❤️", "Red Heart", EmojiCategory.SYMBOLS, listOf("heart","love")),
        EmojiItem("orange_heart", "🧡", "Orange Heart", EmojiCategory.SYMBOLS, listOf("heart","orange")),
        EmojiItem("yellow_heart", "💛", "Yellow Heart", EmojiCategory.SYMBOLS, listOf("heart","yellow")),
        EmojiItem("green_heart", "💚", "Green Heart", EmojiCategory.SYMBOLS, listOf("heart","green")),
        EmojiItem("blue_heart", "💙", "Blue Heart", EmojiCategory.SYMBOLS, listOf("heart","blue")),
        EmojiItem("purple_heart", "💜", "Purple Heart", EmojiCategory.SYMBOLS, listOf("heart","purple")),
        EmojiItem("black_heart", "🖤", "Black Heart", EmojiCategory.SYMBOLS, listOf("heart","black")),
        EmojiItem("broken_heart", "💔", "Broken Heart", EmojiCategory.SYMBOLS, listOf("heart","broken")),
        EmojiItem("fire", "🔥", "Fire", EmojiCategory.SYMBOLS, listOf("fire","hot")),
        EmojiItem("sparkles", "✨", "Sparkles", EmojiCategory.SYMBOLS, listOf("sparkle","shine")),
        EmojiItem("star", "⭐", "Star", EmojiCategory.SYMBOLS, listOf("star","favorite")),
        EmojiItem("check", "✅", "Check Mark", EmojiCategory.SYMBOLS, listOf("check","done")),
        EmojiItem("cross", "❌", "Cross Mark", EmojiCategory.SYMBOLS, listOf("cross","no")),
        EmojiItem("warning", "⚠️", "Warning", EmojiCategory.SYMBOLS, listOf("warning","alert")),
        EmojiItem("100", "💯", "Hundred Points", EmojiCategory.SYMBOLS, listOf("100","perfect")),
        EmojiItem("zzz", "💤", "Zzz", EmojiCategory.SYMBOLS, listOf("sleep","tired")),
        EmojiItem("boom", "💥", "Collision", EmojiCategory.SYMBOLS, listOf("boom","explosion")),
        EmojiItem("speech", "💬", "Speech Bubble", EmojiCategory.SYMBOLS, listOf("speech","chat")),
        EmojiItem("sos", "🆘", "SOS", EmojiCategory.SYMBOLS, listOf("sos","emergency")),
        EmojiItem("new", "🆕", "New", EmojiCategory.SYMBOLS, listOf("new","fresh")),

        // Medieval & Fantasy
        EmojiItem("med_swords",  "⚔️", "Crossed Swords",   EmojiCategory.MEDIEVAL, listOf("sword","battle","fight","medieval")),
        EmojiItem("med_dagger",  "🗡️", "Dagger",           EmojiCategory.MEDIEVAL, listOf("knife","stab","weapon")),
        EmojiItem("med_shield",  "🛡️", "Shield",           EmojiCategory.MEDIEVAL, listOf("defend","protect","armor")),
        EmojiItem("med_castle",  "🏰", "Castle",           EmojiCategory.MEDIEVAL, listOf("fortress","kingdom","medieval")),
        EmojiItem("med_crown",   "👑", "Crown",            EmojiCategory.MEDIEVAL, listOf("king","queen","royalty")),
        EmojiItem("med_prince",  "🤴", "Prince",           EmojiCategory.MEDIEVAL, listOf("royal","king","boy"), true, skinTones("🤴")),
        EmojiItem("med_princess","👸", "Princess",         EmojiCategory.MEDIEVAL, listOf("royal","queen","girl"), true, skinTones("👸")),
        EmojiItem("med_wizard",  "🧙", "Wizard",           EmojiCategory.MEDIEVAL, listOf("mage","sorcerer","magic"), true, skinTones("🧙")),
        EmojiItem("med_elf",     "🧝", "Elf",              EmojiCategory.MEDIEVAL, listOf("fairy","forest","fantasy"), true, skinTones("🧝")),
        EmojiItem("med_vampire", "🧛", "Vampire",          EmojiCategory.MEDIEVAL, listOf("dracula","blood","undead"), true, skinTones("🧛")),
        EmojiItem("med_zombie",  "🧟", "Zombie",           EmojiCategory.MEDIEVAL, listOf("undead","walking dead")),
        EmojiItem("med_genie",   "🧞", "Genie",            EmojiCategory.MEDIEVAL, listOf("wish","lamp","magic")),
        EmojiItem("med_unicorn", "🦄", "Unicorn",          EmojiCategory.MEDIEVAL, listOf("horse","magic","rainbow")),
        EmojiItem("med_dragon",  "🐉", "Dragon",           EmojiCategory.MEDIEVAL, listOf("fire","beast","fantasy")),
        EmojiItem("med_bow",     "🏹", "Bow and Arrow",    EmojiCategory.MEDIEVAL, listOf("arrow","hunt","archery")),
        EmojiItem("med_wand",    "🪄", "Magic Wand",       EmojiCategory.MEDIEVAL, listOf("magic","spell","trick")),
        EmojiItem("med_crystal", "🔮", "Crystal Ball",     EmojiCategory.MEDIEVAL, listOf("fortune","predict","magic")),
        EmojiItem("med_scroll",  "📜", "Scroll",           EmojiCategory.MEDIEVAL, listOf("parchment","ancient","text")),
        EmojiItem("med_candle",  "🕯️", "Candle",          EmojiCategory.MEDIEVAL, listOf("light","flame","wax")),
        EmojiItem("med_key2",    "🗝️", "Old Key",         EmojiCategory.MEDIEVAL, listOf("ancient","lock","open")),
        EmojiItem("med_potion",  "⚗️", "Alembic",         EmojiCategory.MEDIEVAL, listOf("potion","alchemy","brew")),
        EmojiItem("med_coin",    "🪙", "Coin",             EmojiCategory.MEDIEVAL, listOf("gold","money","treasure")),
        EmojiItem("med_scales",  "⚖️", "Balance Scale",   EmojiCategory.MEDIEVAL, listOf("justice","law","judge")),
        EmojiItem("med_blood",   "🩸", "Drop of Blood",   EmojiCategory.MEDIEVAL, listOf("blood","wound","battle")),
        EmojiItem("med_trident", "🔱", "Trident Emblem",  EmojiCategory.MEDIEVAL, listOf("poseidon","sea","power")),

        // 420
        EmojiItem("herb_herb",   "🌿", "Herb",             EmojiCategory.HERB, listOf("plant","green","leaf","nature")),
        EmojiItem("herb_leaves", "🍃", "Falling Leaf",     EmojiCategory.HERB, listOf("leaf","green","nature")),
        EmojiItem("herb_sprout", "🌱", "Seedling",         EmojiCategory.HERB, listOf("grow","plant","sprout")),
        EmojiItem("herb_tree2",  "🌲", "Evergreen Tree",   EmojiCategory.HERB, listOf("pine","forest","green")),
        EmojiItem("herb_pot",    "🪴", "Potted Plant",     EmojiCategory.HERB, listOf("plant","grow","indoor")),
        EmojiItem("herb_wind",   "💨", "Wind",             EmojiCategory.HERB, listOf("air","blow","smoke")),
        EmojiItem("herb_fire2",  "🔥", "Fire",             EmojiCategory.HERB, listOf("blaze","hot","light")),
        EmojiItem("herb_exhale", "😮‍💨","Face Exhaling",  EmojiCategory.HERB, listOf("exhale","breathe","sigh")),
        EmojiItem("herb_relax",  "😌", "Relieved Face",   EmojiCategory.HERB, listOf("calm","peace","chill")),
        EmojiItem("herb_drool",  "🤤", "Drooling Face",   EmojiCategory.HERB, listOf("hungry","munchies","want")),
        EmojiItem("herb_pizza2", "🍕", "Pizza",            EmojiCategory.HERB, listOf("munchies","food","snack")),
        EmojiItem("herb_burger2","🍔", "Hamburger",        EmojiCategory.HERB, listOf("munchies","food","snack")),
        EmojiItem("herb_fries2", "🍟", "French Fries",     EmojiCategory.HERB, listOf("munchies","snack","salty")),
        EmojiItem("herb_cookie2","🍪", "Cookie",           EmojiCategory.HERB, listOf("munchies","sweet","snack")),
        EmojiItem("herb_cupcake","🧁", "Cupcake",          EmojiCategory.HERB, listOf("sweet","munchies","dessert")),
        EmojiItem("herb_choc",   "🍫", "Chocolate",        EmojiCategory.HERB, listOf("sweet","candy","munchies")),
        EmojiItem("herb_sleep",  "😴", "Sleeping",         EmojiCategory.HERB, listOf("sleep","tired","zzz")),
        EmojiItem("herb_cloud",  "💭", "Thought Bubble",   EmojiCategory.HERB, listOf("think","dream","idea")),
        EmojiItem("herb_rainbow","🌈", "Rainbow",          EmojiCategory.HERB, listOf("colors","vibe","peace")),
        EmojiItem("herb_peace",  "☮️", "Peace Symbol",    EmojiCategory.HERB, listOf("peace","love","chill")),
        EmojiItem("herb_meditate","🧘","Lotus Position",   EmojiCategory.HERB, listOf("meditate","relax","zen"), true, skinTones("🧘")),
        EmojiItem("herb_green",  "💚", "Green Heart",      EmojiCategory.HERB, listOf("love","green","nature")),
        EmojiItem("herb_sun2",   "🌻", "Sunflower",        EmojiCategory.HERB, listOf("sunshine","happy","vibe")),
        EmojiItem("herb_couch",  "🛋️", "Couch",           EmojiCategory.HERB, listOf("relax","chill","lazy")),
        EmojiItem("herb_moon2",  "🌙", "Moon",             EmojiCategory.HERB, listOf("night","chill","vibes")),

        // Sci-Fi
        EmojiItem("sci_ufo",     "🛸", "Flying Saucer",   EmojiCategory.SCIFI, listOf("alien","ufo","abduct")),
        EmojiItem("sci_rocket2", "🚀", "Rocket",          EmojiCategory.SCIFI, listOf("space","launch","nasa")),
        EmojiItem("sci_invader", "👾", "Alien Monster",   EmojiCategory.SCIFI, listOf("game","pixel","invader")),
        EmojiItem("sci_alien",   "👽", "Alien",           EmojiCategory.SCIFI, listOf("extraterrestrial","space")),
        EmojiItem("sci_robot",   "🤖", "Robot",           EmojiCategory.SCIFI, listOf("android","ai","machine")),
        EmojiItem("sci_galaxy",  "🌌", "Milky Way",       EmojiCategory.SCIFI, listOf("galaxy","stars","cosmos")),
        EmojiItem("sci_planet",  "🪐", "Ringed Planet",   EmojiCategory.SCIFI, listOf("saturn","orbit","space")),
        EmojiItem("sci_comet",   "☄️", "Comet",           EmojiCategory.SCIFI, listOf("meteor","asteroid","sky")),
        EmojiItem("sci_star2",   "🌠", "Shooting Star",   EmojiCategory.SCIFI, listOf("wish","star","night")),
        EmojiItem("sci_scope",   "🔭", "Telescope",       EmojiCategory.SCIFI, listOf("observe","stars","science")),
        EmojiItem("sci_satellite","🛰️","Satellite",       EmojiCategory.SCIFI, listOf("orbit","space","signal")),
        EmojiItem("sci_dish",    "📡", "Satellite Dish",  EmojiCategory.SCIFI, listOf("signal","broadcast","alien")),
        EmojiItem("sci_dna",     "🧬", "DNA",             EmojiCategory.SCIFI, listOf("genetics","biology","clone")),
        EmojiItem("sci_atom",    "⚛️", "Atom Symbol",     EmojiCategory.SCIFI, listOf("nuclear","physics","science")),
        EmojiItem("sci_arm",     "🦾", "Mechanical Arm",  EmojiCategory.SCIFI, listOf("prosthetic","robot","cyber")),
        EmojiItem("sci_mindblown","🤯","Exploding Head",  EmojiCategory.SCIFI, listOf("mindblown","wow","shock")),
        EmojiItem("sci_micro",   "🔬", "Microscope",      EmojiCategory.SCIFI, listOf("science","lab","tiny")),
        EmojiItem("sci_bolt",    "⚡", "Lightning Bolt",  EmojiCategory.SCIFI, listOf("energy","power","electric")),
        EmojiItem("sci_vortex",  "🌀", "Cyclone",         EmojiCategory.SCIFI, listOf("vortex","warp","spiral")),
        EmojiItem("sci_hole",    "🕳️", "Hole",            EmojiCategory.SCIFI, listOf("black hole","void","empty")),
        EmojiItem("sci_globe",   "🌐", "Globe",           EmojiCategory.SCIFI, listOf("network","world","internet")),
        EmojiItem("sci_disk",    "💾", "Floppy Disk",     EmojiCategory.SCIFI, listOf("save","data","retro")),
        EmojiItem("sci_battery", "🔋", "Battery",         EmojiCategory.SCIFI, listOf("power","charge","energy")),
        EmojiItem("sci_flask",   "🧪", "Test Tube",       EmojiCategory.SCIFI, listOf("lab","experiment","science")),
        EmojiItem("sci_explosion","💥","Explosion",        EmojiCategory.SCIFI, listOf("boom","blast","impact")),

        // Horror
        EmojiItem("hor_ghost2",  "👻", "Ghost",           EmojiCategory.HORROR, listOf("spooky","haunt","spirit")),
        EmojiItem("hor_skull2",  "💀", "Skull",           EmojiCategory.HORROR, listOf("death","dead","bones")),
        EmojiItem("hor_bones",   "☠️", "Skull Crossbones",EmojiCategory.HORROR, listOf("poison","pirate","death")),
        EmojiItem("hor_zombie2", "🧟", "Zombie",          EmojiCategory.HORROR, listOf("undead","walking dead")),
        EmojiItem("hor_vampire2","🧛", "Vampire",         EmojiCategory.HORROR, listOf("dracula","blood","bite"), true, skinTones("🧛")),
        EmojiItem("hor_spider",  "🕷️", "Spider",         EmojiCategory.HORROR, listOf("web","creepy","eight legs")),
        EmojiItem("hor_web",     "🕸️", "Spider Web",     EmojiCategory.HORROR, listOf("trap","spider","creepy")),
        EmojiItem("hor_bat",     "🦇", "Bat",             EmojiCategory.HORROR, listOf("vampire","night","cave")),
        EmojiItem("hor_grave",   "🪦", "Headstone",       EmojiCategory.HORROR, listOf("grave","cemetery","dead")),
        EmojiItem("hor_coffin",  "⚰️", "Coffin",         EmojiCategory.HORROR, listOf("dead","buried","vampire")),
        EmojiItem("hor_blood2",  "🩸", "Blood Drop",      EmojiCategory.HORROR, listOf("blood","wound","horror")),
        EmojiItem("hor_scream",  "😱", "Screaming Face",  EmojiCategory.HORROR, listOf("scream","scared","fear")),
        EmojiItem("hor_haunted", "🏚️", "Derelict House", EmojiCategory.HORROR, listOf("haunted","abandoned","ghost")),
        EmojiItem("hor_knife",   "🔪", "Knife",           EmojiCategory.HORROR, listOf("stab","blade","horror")),
        EmojiItem("hor_chains",  "⛓️", "Chains",         EmojiCategory.HORROR, listOf("bound","prisoner","trap")),
        EmojiItem("hor_night",   "🌑", "New Moon",        EmojiCategory.HORROR, listOf("dark","night","black")),
        EmojiItem("hor_demon",   "😈", "Smiling Imp",     EmojiCategory.HORROR, listOf("devil","evil","mischief")),
        EmojiItem("hor_bone",    "🦴", "Bone",            EmojiCategory.HORROR, listOf("skeleton","dog","dead")),
        EmojiItem("hor_brain2",  "🧠", "Brain",           EmojiCategory.HORROR, listOf("zombie","organ","mind")),
        EmojiItem("hor_eye",     "👁️", "Eye",            EmojiCategory.HORROR, listOf("watching","spy","creepy")),
        EmojiItem("hor_fog",     "🌫️", "Fog",            EmojiCategory.HORROR, listOf("mist","haze","eerie")),
        EmojiItem("hor_jack",    "🎃", "Jack-O-Lantern",  EmojiCategory.HORROR, listOf("halloween","pumpkin","scary")),
        EmojiItem("hor_virus",   "🦠", "Microbe",         EmojiCategory.HORROR, listOf("virus","germ","plague")),
        EmojiItem("hor_tornado", "🌪️", "Tornado",        EmojiCategory.HORROR, listOf("storm","destruction","fear")),
        EmojiItem("hor_axe",     "🪓", "Axe",             EmojiCategory.HORROR, listOf("chop","horror","weapon")),

        // Music
        EmojiItem("mus_note",    "🎵", "Musical Note",    EmojiCategory.MUSIC, listOf("music","sound","melody")),
        EmojiItem("mus_notes",   "🎶", "Musical Notes",   EmojiCategory.MUSIC, listOf("music","song","melody")),
        EmojiItem("mus_guitar2", "🎸", "Guitar",          EmojiCategory.MUSIC, listOf("rock","string","band")),
        EmojiItem("mus_piano",   "🎹", "Piano",           EmojiCategory.MUSIC, listOf("keyboard","classic","keys")),
        EmojiItem("mus_trumpet", "🎺", "Trumpet",         EmojiCategory.MUSIC, listOf("jazz","brass","horn")),
        EmojiItem("mus_violin",  "🎻", "Violin",          EmojiCategory.MUSIC, listOf("strings","classic","fiddle")),
        EmojiItem("mus_drum",    "🥁", "Drum",            EmojiCategory.MUSIC, listOf("beat","rhythm","percussion")),
        EmojiItem("mus_bongo",   "🪘", "Long Drum",       EmojiCategory.MUSIC, listOf("bongo","conga","beat")),
        EmojiItem("mus_mic2",    "🎤", "Microphone",      EmojiCategory.MUSIC, listOf("sing","perform","karaoke")),
        EmojiItem("mus_headphones2","🎧","Headphones",    EmojiCategory.MUSIC, listOf("listen","audio","music")),
        EmojiItem("mus_sheet",   "🎼", "Musical Score",   EmojiCategory.MUSIC, listOf("sheet","compose","notes")),
        EmojiItem("mus_cd",      "💿", "Optical Disk",    EmojiCategory.MUSIC, listOf("album","record","cd")),
        EmojiItem("mus_radio",   "📻", "Radio",           EmojiCategory.MUSIC, listOf("broadcast","station","tune")),
        EmojiItem("mus_studio",  "🎙️", "Studio Mic",     EmojiCategory.MUSIC, listOf("record","broadcast","podcast")),
        EmojiItem("mus_sax",     "🎷", "Saxophone",       EmojiCategory.MUSIC, listOf("jazz","woodwind","blues")),
        EmojiItem("mus_accordion","🪗", "Accordion",      EmojiCategory.MUSIC, listOf("folk","squeeze","polka")),
        EmojiItem("mus_banjo",   "🪕", "Banjo",           EmojiCategory.MUSIC, listOf("country","strings","folk")),
        EmojiItem("mus_mixer",   "🎚️", "Level Slider",   EmojiCategory.MUSIC, listOf("mix","adjust","audio")),
        EmojiItem("mus_controls","🎛️", "Control Knobs",  EmojiCategory.MUSIC, listOf("mix","dj","produce")),
        EmojiItem("mus_speaker", "🔊", "Speaker",         EmojiCategory.MUSIC, listOf("loud","audio","sound")),
        EmojiItem("mus_disco",   "🪩", "Mirror Ball",     EmojiCategory.MUSIC, listOf("disco","dance","party")),
        EmojiItem("mus_theater", "🎭", "Performing Arts", EmojiCategory.MUSIC, listOf("drama","perform","show")),
        EmojiItem("mus_horn",    "📯", "Postal Horn",     EmojiCategory.MUSIC, listOf("horn","announce","fanfare")),
        EmojiItem("mus_clapper", "🎬", "Clapperboard",    EmojiCategory.MUSIC, listOf("film","action","movie")),
        EmojiItem("mus_circus",  "🎪", "Circus Tent",     EmojiCategory.MUSIC, listOf("show","perform","circus")),

        // Ocean
        EmojiItem("sea_wave2",   "🌊", "Wave",            EmojiCategory.OCEAN, listOf("ocean","sea","surf","water")),
        EmojiItem("sea_beach2",  "🏖️", "Beach",          EmojiCategory.OCEAN, listOf("sand","sun","vacation")),
        EmojiItem("sea_shell",   "🐚", "Spiral Shell",    EmojiCategory.OCEAN, listOf("shell","beach","ocean")),
        EmojiItem("sea_crab",    "🦀", "Crab",            EmojiCategory.OCEAN, listOf("seafood","red","claws")),
        EmojiItem("sea_lobster", "🦞", "Lobster",         EmojiCategory.OCEAN, listOf("seafood","red","ocean")),
        EmojiItem("sea_shrimp",  "🦐", "Shrimp",          EmojiCategory.OCEAN, listOf("seafood","small","pink")),
        EmojiItem("sea_octopus", "🐙", "Octopus",         EmojiCategory.OCEAN, listOf("tentacles","ink","sea")),
        EmojiItem("sea_squid",   "🦑", "Squid",           EmojiCategory.OCEAN, listOf("calamari","ink","tentacles")),
        EmojiItem("sea_fish",    "🐟", "Fish",            EmojiCategory.OCEAN, listOf("swim","ocean","seafood")),
        EmojiItem("sea_tropfish","🐠", "Tropical Fish",   EmojiCategory.OCEAN, listOf("colorful","reef","aquarium")),
        EmojiItem("sea_blowfish","🐡", "Blowfish",        EmojiCategory.OCEAN, listOf("puffer","spiky","poison")),
        EmojiItem("sea_shark",   "🦈", "Shark",           EmojiCategory.OCEAN, listOf("predator","fin","danger")),
        EmojiItem("sea_whale",   "🐳", "Whale",           EmojiCategory.OCEAN, listOf("big","mammal","spout")),
        EmojiItem("sea_dolphin", "🐬", "Dolphin",         EmojiCategory.OCEAN, listOf("smart","jump","mammal")),
        EmojiItem("sea_sailboat","⛵", "Sailboat",        EmojiCategory.OCEAN, listOf("sail","wind","voyage")),
        EmojiItem("sea_surf",    "🏄", "Surfing",         EmojiCategory.OCEAN, listOf("surf","wave","sport"), true, skinTones("🏄")),
        EmojiItem("sea_dive",    "🤿", "Diving Mask",     EmojiCategory.OCEAN, listOf("scuba","snorkel","dive")),
        EmojiItem("sea_island",  "🏝️", "Desert Island",  EmojiCategory.OCEAN, listOf("tropical","palm","paradise")),
        EmojiItem("sea_anchor",  "⚓", "Anchor",          EmojiCategory.OCEAN, listOf("ship","dock","navy")),
        EmojiItem("sea_coral",   "🪸", "Coral",           EmojiCategory.OCEAN, listOf("reef","colorful","ocean")),
        EmojiItem("sea_seal",    "🦭", "Seal",            EmojiCategory.OCEAN, listOf("mammal","flipper","arctic")),
        EmojiItem("sea_palm",    "🌴", "Palm Tree",       EmojiCategory.OCEAN, listOf("beach","tropical","coconut")),
        EmojiItem("sea_mermaid", "🧜", "Mermaid",         EmojiCategory.OCEAN, listOf("myth","sea","fantasy"), true, skinTones("🧜")),
        EmojiItem("sea_flamingo","🦩", "Flamingo",        EmojiCategory.OCEAN, listOf("pink","bird","tropical")),
        EmojiItem("sea_whale2",  "🐋", "Whale Spout",     EmojiCategory.OCEAN, listOf("blue whale","ocean","big"))
    )

    fun byCategory(category: EmojiCategory) = all.filter { it.category == category }

    fun search(query: String): List<EmojiItem> {
        val q = query.lowercase()
        return all.filter {
            it.name.lowercase().contains(q) || it.keywords.any { k -> k.contains(q) }
        }
    }
}
