package com.moji.keyboard

data class EmojiItem(
    val id: String,
    val emoji: String,
    val name: String,
    val category: EmojiCategory,
    val keywords: List<String>,
    val hasSkinTones: Boolean = false,
    val skinToneVariants: List<String> = emptyList()
)

enum class EmojiCategory(val label: String, val icon: String) {
    RECENT("Recent", "🕐"),
    SMILEYS("Smileys", "😀"),
    PEOPLE("People", "👋"),
    NATURE("Nature", "🌸"),
    FOOD("Food", "🍎"),
    TRAVEL("Travel", "✈️"),
    ACTIVITIES("Activities", "⚽"),
    OBJECTS("Objects", "💡"),
    SYMBOLS("Symbols", "❤️")
}

object EmojiDatabase {
    private fun skinTones(base: String) = listOf(
        "$base🏻", "$base🏼", "$base🏽",
        "$base🏾", "$base🏿"
    )

    val all: List<EmojiItem> = listOf(
        // Smileys
        EmojiItem("grinning", "😀", "Grinning Face", EmojiCategory.SMILEYS, listOf("smile","happy","face")),
        EmojiItem("joy", "😂", "Face with Tears of Joy", EmojiCategory.SMILEYS, listOf("laugh","happy","cry")),
        EmojiItem("rofl", "🤣", "Rolling on Floor Laughing", EmojiCategory.SMILEYS, listOf("laugh","funny")),
        EmojiItem("smile", "😊", "Smiling Face", EmojiCategory.SMILEYS, listOf("smile","happy")),
        EmojiItem("wink", "😉", "Winking Face", EmojiCategory.SMILEYS, listOf("wink","smile")),
        EmojiItem("heart_eyes", "😍", "Heart Eyes", EmojiCategory.SMILEYS, listOf("love","heart")),
        EmojiItem("star_eyes", "🤩", "Star Eyes", EmojiCategory.SMILEYS, listOf("star","excited")),
        EmojiItem("kiss", "😘", "Kissing Heart", EmojiCategory.SMILEYS, listOf("kiss","love")),
        EmojiItem("thinking", "🤔", "Thinking Face", EmojiCategory.SMILEYS, listOf("think","hmm")),
        EmojiItem("flushed", "😳", "Flushed Face", EmojiCategory.SMILEYS, listOf("blush","shy")),
        EmojiItem("sob", "😭", "Loudly Crying", EmojiCategory.SMILEYS, listOf("cry","sad")),
        EmojiItem("angry", "😠", "Angry Face", EmojiCategory.SMILEYS, listOf("angry","mad")),
        EmojiItem("rage", "😡", "Pouting Face", EmojiCategory.SMILEYS, listOf("angry","rage")),
        EmojiItem("skull", "💀", "Skull", EmojiCategory.SMILEYS, listOf("dead","skull")),
        EmojiItem("ghost", "👻", "Ghost", EmojiCategory.SMILEYS, listOf("ghost","boo")),
        EmojiItem("alien", "👽", "Alien", EmojiCategory.SMILEYS, listOf("alien","space")),
        EmojiItem("fire_eyes", "🤬", "Face with Symbols", EmojiCategory.SMILEYS, listOf("angry","censored")),
        EmojiItem("hot", "🥵", "Hot Face", EmojiCategory.SMILEYS, listOf("hot","warm")),
        EmojiItem("cold", "🥶", "Cold Face", EmojiCategory.SMILEYS, listOf("cold","freezing")),
        EmojiItem("sleeping", "😴", "Sleeping", EmojiCategory.SMILEYS, listOf("sleep","tired")),
        EmojiItem("sick", "🤒", "Sick Face", EmojiCategory.SMILEYS, listOf("sick","ill")),
        EmojiItem("mask", "😷", "Medical Mask", EmojiCategory.SMILEYS, listOf("sick","mask")),
        EmojiItem("cowboy", "🤠", "Cowboy Hat", EmojiCategory.SMILEYS, listOf("cowboy","hat")),
        EmojiItem("partying", "🥳", "Partying Face", EmojiCategory.SMILEYS, listOf("party","celebrate")),
        EmojiItem("monocle", "🧐", "Monocle Face", EmojiCategory.SMILEYS, listOf("monocle","fancy")),
        EmojiItem("nerd", "🤓", "Nerd Face", EmojiCategory.SMILEYS, listOf("nerd","glasses")),
        EmojiItem("sunglasses", "😎", "Sunglasses", EmojiCategory.SMILEYS, listOf("cool","sunglasses")),
        EmojiItem("clown", "🤡", "Clown Face", EmojiCategory.SMILEYS, listOf("clown","joker")),
        EmojiItem("poop", "💩", "Pile of Poo", EmojiCategory.SMILEYS, listOf("poop","funny")),
        EmojiItem("rainbow_flag", "🏳️‍🌈", "Rainbow Flag", EmojiCategory.SMILEYS, listOf("pride","rainbow")),

        // People
        EmojiItem("wave", "👋", "Waving Hand", EmojiCategory.PEOPLE, listOf("wave","hello"), true, skinTones("👋")),
        EmojiItem("thumbsup", "👍", "Thumbs Up", EmojiCategory.PEOPLE, listOf("thumbs","good"), true, skinTones("👍")),
        EmojiItem("thumbsdown", "👎", "Thumbs Down", EmojiCategory.PEOPLE, listOf("thumbs","bad"), true, skinTones("👎")),
        EmojiItem("clap", "👏", "Clapping Hands", EmojiCategory.PEOPLE, listOf("clap","applause"), true, skinTones("👏")),
        EmojiItem("raised_hands", "🙌", "Raising Hands", EmojiCategory.PEOPLE, listOf("celebrate","party"), true, skinTones("🙌")),
        EmojiItem("fist", "✊", "Raised Fist", EmojiCategory.PEOPLE, listOf("fist","power"), true, skinTones("✊")),
        EmojiItem("punch", "👊", "Oncoming Fist", EmojiCategory.PEOPLE, listOf("punch","hit"), true, skinTones("👊")),
        EmojiItem("ok_hand", "👌", "OK Hand", EmojiCategory.PEOPLE, listOf("ok","good"), true, skinTones("👌")),
        EmojiItem("peace", "✌️", "Victory Hand", EmojiCategory.PEOPLE, listOf("peace","victory"), true, skinTones("✌️")),
        EmojiItem("love_you", "🤟", "Love You Gesture", EmojiCategory.PEOPLE, listOf("love","rock"), true, skinTones("🤟")),
        EmojiItem("metal", "🤘", "Sign of Horns", EmojiCategory.PEOPLE, listOf("rock","metal"), true, skinTones("🤘")),
        EmojiItem("call_me", "🤙", "Call Me Hand", EmojiCategory.PEOPLE, listOf("call","phone"), true, skinTones("🤙")),
        EmojiItem("point_right", "👉", "Pointing Right", EmojiCategory.PEOPLE, listOf("point","right"), true, skinTones("👉")),
        EmojiItem("point_left", "👈", "Pointing Left", EmojiCategory.PEOPLE, listOf("point","left"), true, skinTones("👈")),
        EmojiItem("point_up", "☝️", "Pointing Up", EmojiCategory.PEOPLE, listOf("point","up"), true, skinTones("☝️")),
        EmojiItem("point_down", "👇", "Pointing Down", EmojiCategory.PEOPLE, listOf("point","down"), true, skinTones("👇")),
        EmojiItem("raised_hand", "✋", "Raised Hand", EmojiCategory.PEOPLE, listOf("hand","stop"), true, skinTones("✋")),
        EmojiItem("vulcan", "🖖", "Vulcan Salute", EmojiCategory.PEOPLE, listOf("spock","peace"), true, skinTones("🖖")),
        EmojiItem("handshake", "🤝", "Handshake", EmojiCategory.PEOPLE, listOf("deal","handshake")),
        EmojiItem("pray", "🙏", "Folded Hands", EmojiCategory.PEOPLE, listOf("pray","thanks"), true, skinTones("🙏")),
        EmojiItem("muscle", "💪", "Flexed Biceps", EmojiCategory.PEOPLE, listOf("strong","muscle"), true, skinTones("💪")),
        EmojiItem("nail_polish", "💅", "Nail Polish", EmojiCategory.PEOPLE, listOf("nails","beauty"), true, skinTones("💅")),
        EmojiItem("ear", "👂", "Ear", EmojiCategory.PEOPLE, listOf("ear","listen"), true, skinTones("👂")),
        EmojiItem("nose", "👃", "Nose", EmojiCategory.PEOPLE, listOf("nose","smell"), true, skinTones("👃")),
        EmojiItem("eyes", "👀", "Eyes", EmojiCategory.PEOPLE, listOf("eyes","look")),
        EmojiItem("brain", "🧠", "Brain", EmojiCategory.PEOPLE, listOf("brain","smart")),
        EmojiItem("heart_organ", "🫀", "Anatomical Heart", EmojiCategory.PEOPLE, listOf("heart","organ")),
        EmojiItem("lungs", "🫁", "Lungs", EmojiCategory.PEOPLE, listOf("lungs","breath")),
        EmojiItem("baby", "👶", "Baby", EmojiCategory.PEOPLE, listOf("baby","child"), true, skinTones("👶")),
        EmojiItem("boy", "👦", "Boy", EmojiCategory.PEOPLE, listOf("boy","child"), true, skinTones("👦")),
        EmojiItem("girl", "👧", "Girl", EmojiCategory.PEOPLE, listOf("girl","child"), true, skinTones("👧")),

        // Nature
        EmojiItem("dog", "🐶", "Dog Face", EmojiCategory.NATURE, listOf("dog","pet")),
        EmojiItem("cat", "🐱", "Cat Face", EmojiCategory.NATURE, listOf("cat","pet")),
        EmojiItem("mouse", "🐭", "Mouse Face", EmojiCategory.NATURE, listOf("mouse","animal")),
        EmojiItem("hamster", "🐹", "Hamster", EmojiCategory.NATURE, listOf("hamster","cute")),
        EmojiItem("rabbit", "🐰", "Rabbit Face", EmojiCategory.NATURE, listOf("rabbit","bunny")),
        EmojiItem("fox", "🦊", "Fox", EmojiCategory.NATURE, listOf("fox","animal")),
        EmojiItem("bear", "🐻", "Bear Face", EmojiCategory.NATURE, listOf("bear","animal")),
        EmojiItem("panda", "🐼", "Panda", EmojiCategory.NATURE, listOf("panda","cute")),
        EmojiItem("koala", "🐨", "Koala", EmojiCategory.NATURE, listOf("koala","australia")),
        EmojiItem("tiger", "🐯", "Tiger Face", EmojiCategory.NATURE, listOf("tiger","animal")),
        EmojiItem("lion", "🦁", "Lion", EmojiCategory.NATURE, listOf("lion","king")),
        EmojiItem("cow", "🐮", "Cow Face", EmojiCategory.NATURE, listOf("cow","animal")),
        EmojiItem("pig", "🐷", "Pig Face", EmojiCategory.NATURE, listOf("pig","oink")),
        EmojiItem("frog", "🐸", "Frog", EmojiCategory.NATURE, listOf("frog","green")),
        EmojiItem("monkey", "🐵", "Monkey Face", EmojiCategory.NATURE, listOf("monkey","ape")),
        EmojiItem("chicken", "🐔", "Chicken", EmojiCategory.NATURE, listOf("chicken","bird")),
        EmojiItem("penguin", "🐧", "Penguin", EmojiCategory.NATURE, listOf("penguin","bird")),
        EmojiItem("bird", "🐦", "Bird", EmojiCategory.NATURE, listOf("bird","fly")),
        EmojiItem("owl", "🦉", "Owl", EmojiCategory.NATURE, listOf("owl","wise")),
        EmojiItem("butterfly", "🦋", "Butterfly", EmojiCategory.NATURE, listOf("butterfly","insect")),
        EmojiItem("flower", "🌸", "Cherry Blossom", EmojiCategory.NATURE, listOf("flower","pink")),
        EmojiItem("rose", "🌹", "Rose", EmojiCategory.NATURE, listOf("rose","love")),
        EmojiItem("sunflower", "🌻", "Sunflower", EmojiCategory.NATURE, listOf("sunflower","flower")),
        EmojiItem("tree", "🌳", "Deciduous Tree", EmojiCategory.NATURE, listOf("tree","nature")),
        EmojiItem("palm", "🌴", "Palm Tree", EmojiCategory.NATURE, listOf("palm","beach")),
        EmojiItem("cactus", "🌵", "Cactus", EmojiCategory.NATURE, listOf("cactus","desert")),
        EmojiItem("mushroom", "🍄", "Mushroom", EmojiCategory.NATURE, listOf("mushroom","fungi")),
        EmojiItem("earth", "🌍", "Earth Globe", EmojiCategory.NATURE, listOf("earth","world")),
        EmojiItem("sun", "☀️", "Sun", EmojiCategory.NATURE, listOf("sun","bright")),
        EmojiItem("moon", "🌙", "Crescent Moon", EmojiCategory.NATURE, listOf("moon","night")),

        // Food
        EmojiItem("apple", "🍎", "Red Apple", EmojiCategory.FOOD, listOf("apple","fruit")),
        EmojiItem("banana", "🍌", "Banana", EmojiCategory.FOOD, listOf("banana","fruit")),
        EmojiItem("grapes", "🍇", "Grapes", EmojiCategory.FOOD, listOf("grapes","fruit")),
        EmojiItem("strawberry", "🍓", "Strawberry", EmojiCategory.FOOD, listOf("strawberry","berry")),
        EmojiItem("watermelon", "🍉", "Watermelon", EmojiCategory.FOOD, listOf("watermelon","summer")),
        EmojiItem("lemon", "🍋", "Lemon", EmojiCategory.FOOD, listOf("lemon","sour")),
        EmojiItem("pizza", "🍕", "Pizza", EmojiCategory.FOOD, listOf("pizza","food")),
        EmojiItem("burger", "🍔", "Hamburger", EmojiCategory.FOOD, listOf("burger","food")),
        EmojiItem("fries", "🍟", "French Fries", EmojiCategory.FOOD, listOf("fries","food")),
        EmojiItem("hotdog", "🌭", "Hot Dog", EmojiCategory.FOOD, listOf("hotdog","sausage")),
        EmojiItem("taco", "🌮", "Taco", EmojiCategory.FOOD, listOf("taco","mexican")),
        EmojiItem("burrito", "🌯", "Burrito", EmojiCategory.FOOD, listOf("burrito","wrap")),
        EmojiItem("sushi", "🍣", "Sushi", EmojiCategory.FOOD, listOf("sushi","japanese")),
        EmojiItem("ramen", "🍜", "Ramen", EmojiCategory.FOOD, listOf("ramen","noodles")),
        EmojiItem("cake", "🎂", "Birthday Cake", EmojiCategory.FOOD, listOf("cake","birthday")),
        EmojiItem("ice_cream", "🍦", "Ice Cream", EmojiCategory.FOOD, listOf("ice cream","sweet")),
        EmojiItem("donut", "🍩", "Donut", EmojiCategory.FOOD, listOf("donut","sweet")),
        EmojiItem("cookie", "🍪", "Cookie", EmojiCategory.FOOD, listOf("cookie","sweet")),
        EmojiItem("coffee", "☕", "Hot Beverage", EmojiCategory.FOOD, listOf("coffee","tea")),
        EmojiItem("beer", "🍺", "Beer Mug", EmojiCategory.FOOD, listOf("beer","drink")),
        EmojiItem("wine", "🍷", "Wine Glass", EmojiCategory.FOOD, listOf("wine","drink")),
        EmojiItem("cocktail", "🍹", "Tropical Drink", EmojiCategory.FOOD, listOf("cocktail","drink")),
        EmojiItem("bubble_tea", "🧋", "Bubble Tea", EmojiCategory.FOOD, listOf("boba","tea")),

        // Travel
        EmojiItem("airplane", "✈️", "Airplane", EmojiCategory.TRAVEL, listOf("fly","travel")),
        EmojiItem("rocket", "🚀", "Rocket", EmojiCategory.TRAVEL, listOf("rocket","space")),
        EmojiItem("car", "🚗", "Automobile", EmojiCategory.TRAVEL, listOf("car","drive")),
        EmojiItem("bus", "🚌", "Bus", EmojiCategory.TRAVEL, listOf("bus","transit")),
        EmojiItem("train", "🚂", "Train", EmojiCategory.TRAVEL, listOf("train","rail")),
        EmojiItem("ship", "🚢", "Ship", EmojiCategory.TRAVEL, listOf("ship","boat")),
        EmojiItem("bicycle", "🚲", "Bicycle", EmojiCategory.TRAVEL, listOf("bike","cycle")),
        EmojiItem("house", "🏠", "House", EmojiCategory.TRAVEL, listOf("home","house")),
        EmojiItem("building", "🏢", "Office Building", EmojiCategory.TRAVEL, listOf("office","building")),
        EmojiItem("hospital", "🏥", "Hospital", EmojiCategory.TRAVEL, listOf("hospital","medical")),
        EmojiItem("school", "🏫", "School", EmojiCategory.TRAVEL, listOf("school","education")),
        EmojiItem("beach", "🏖️", "Beach", EmojiCategory.TRAVEL, listOf("beach","sand")),
        EmojiItem("mountain", "⛰️", "Mountain", EmojiCategory.TRAVEL, listOf("mountain","hike")),
        EmojiItem("rainbow", "🌈", "Rainbow", EmojiCategory.TRAVEL, listOf("rainbow","colorful")),
        EmojiItem("camping", "🏕️", "Camping", EmojiCategory.TRAVEL, listOf("camp","tent")),

        // Activities
        EmojiItem("soccer", "⚽", "Soccer Ball", EmojiCategory.ACTIVITIES, listOf("soccer","sports")),
        EmojiItem("basketball", "🏀", "Basketball", EmojiCategory.ACTIVITIES, listOf("basketball","sports")),
        EmojiItem("football", "🏈", "Football", EmojiCategory.ACTIVITIES, listOf("football","sports")),
        EmojiItem("baseball", "⚾", "Baseball", EmojiCategory.ACTIVITIES, listOf("baseball","sports")),
        EmojiItem("tennis", "🎾", "Tennis", EmojiCategory.ACTIVITIES, listOf("tennis","sports")),
        EmojiItem("volleyball", "🏐", "Volleyball", EmojiCategory.ACTIVITIES, listOf("volleyball","sports")),
        EmojiItem("bowling", "🎳", "Bowling", EmojiCategory.ACTIVITIES, listOf("bowling","sports")),
        EmojiItem("golf", "⛳", "Golf", EmojiCategory.ACTIVITIES, listOf("golf","sports")),
        EmojiItem("gaming", "🎮", "Video Game", EmojiCategory.ACTIVITIES, listOf("game","gaming")),
        EmojiItem("guitar", "🎸", "Guitar", EmojiCategory.ACTIVITIES, listOf("guitar","music")),
        EmojiItem("music", "🎵", "Musical Note", EmojiCategory.ACTIVITIES, listOf("music","note")),
        EmojiItem("mic", "🎤", "Microphone", EmojiCategory.ACTIVITIES, listOf("mic","sing")),
        EmojiItem("art", "🎨", "Artist Palette", EmojiCategory.ACTIVITIES, listOf("art","paint")),
        EmojiItem("movie", "🎬", "Clapperboard", EmojiCategory.ACTIVITIES, listOf("movie","film")),
        EmojiItem("trophy", "🏆", "Trophy", EmojiCategory.ACTIVITIES, listOf("trophy","win")),

        // Objects
        EmojiItem("phone", "📱", "Mobile Phone", EmojiCategory.OBJECTS, listOf("phone","mobile")),
        EmojiItem("laptop", "💻", "Laptop", EmojiCategory.OBJECTS, listOf("laptop","computer")),
        EmojiItem("camera", "📷", "Camera", EmojiCategory.OBJECTS, listOf("camera","photo")),
        EmojiItem("tv", "📺", "Television", EmojiCategory.OBJECTS, listOf("tv","screen")),
        EmojiItem("headphones", "🎧", "Headphones", EmojiCategory.OBJECTS, listOf("headphones","music")),
        EmojiItem("bulb", "💡", "Light Bulb", EmojiCategory.OBJECTS, listOf("idea","light")),
        EmojiItem("book", "📖", "Open Book", EmojiCategory.OBJECTS, listOf("book","read")),
        EmojiItem("money", "💰", "Money Bag", EmojiCategory.OBJECTS, listOf("money","rich")),
        EmojiItem("gift", "🎁", "Gift", EmojiCategory.OBJECTS, listOf("gift","present")),
        EmojiItem("key", "🔑", "Key", EmojiCategory.OBJECTS, listOf("key","lock")),
        EmojiItem("lock", "🔒", "Locked", EmojiCategory.OBJECTS, listOf("lock","secure")),
        EmojiItem("hammer", "🔨", "Hammer", EmojiCategory.OBJECTS, listOf("hammer","tool")),
        EmojiItem("pill", "💊", "Pill", EmojiCategory.OBJECTS, listOf("pill","medicine")),
        EmojiItem("scissors", "✂️", "Scissors", EmojiCategory.OBJECTS, listOf("cut","scissors")),

        // Symbols
        EmojiItem("heart", "❤️", "Red Heart", EmojiCategory.SYMBOLS, listOf("heart","love")),
        EmojiItem("orange_heart", "🧡", "Orange Heart", EmojiCategory.SYMBOLS, listOf("heart","orange")),
        EmojiItem("yellow_heart", "💛", "Yellow Heart", EmojiCategory.SYMBOLS, listOf("heart","yellow")),
        EmojiItem("green_heart", "💚", "Green Heart", EmojiCategory.SYMBOLS, listOf("heart","green")),
        EmojiItem("blue_heart", "💙", "Blue Heart", EmojiCategory.SYMBOLS, listOf("heart","blue")),
        EmojiItem("purple_heart", "💜", "Purple Heart", EmojiCategory.SYMBOLS, listOf("heart","purple")),
        EmojiItem("black_heart", "🖤", "Black Heart", EmojiCategory.SYMBOLS, listOf("heart","black")),
        EmojiItem("broken_heart", "💔", "Broken Heart", EmojiCategory.SYMBOLS, listOf("heart","broken")),
        EmojiItem("fire", "🔥", "Fire", EmojiCategory.SYMBOLS, listOf("fire","hot")),
        EmojiItem("sparkles", "✨", "Sparkles", EmojiCategory.SYMBOLS, listOf("sparkle","shine")),
        EmojiItem("star", "⭐", "Star", EmojiCategory.SYMBOLS, listOf("star","favorite")),
        EmojiItem("check", "✅", "Check Mark", EmojiCategory.SYMBOLS, listOf("check","done")),
        EmojiItem("cross", "❌", "Cross Mark", EmojiCategory.SYMBOLS, listOf("cross","no")),
        EmojiItem("warning", "⚠️", "Warning", EmojiCategory.SYMBOLS, listOf("warning","alert")),
        EmojiItem("100", "💯", "Hundred Points", EmojiCategory.SYMBOLS, listOf("100","perfect")),
        EmojiItem("zzz", "💤", "Zzz", EmojiCategory.SYMBOLS, listOf("sleep","tired")),
        EmojiItem("boom", "💥", "Collision", EmojiCategory.SYMBOLS, listOf("boom","explosion")),
        EmojiItem("speech", "💬", "Speech Bubble", EmojiCategory.SYMBOLS, listOf("speech","chat")),
        EmojiItem("sos", "🆘", "SOS", EmojiCategory.SYMBOLS, listOf("sos","emergency")),
        EmojiItem("new", "🆕", "New", EmojiCategory.SYMBOLS, listOf("new","fresh"))
    )

    fun byCategory(category: EmojiCategory) = all.filter { it.category == category }

    fun search(query: String): List<EmojiItem> {
        val q = query.lowercase()
        return all.filter {
            it.name.lowercase().contains(q) || it.keywords.any { k -> k.contains(q) }
        }
    }
}
