import { Emoji, EmojiCategory, SkinTone } from './types';

const SKIN_TONE_MODIFIERS = [SkinTone.LIGHT, SkinTone.MEDIUM_LIGHT, SkinTone.MEDIUM, SkinTone.MEDIUM_DARK, SkinTone.DARK];

const applySkinTones = (baseEmoji: string): string[] => {
  return SKIN_TONE_MODIFIERS.map(tone => baseEmoji + tone);
};

const emojis: Emoji[] = [
  // Smileys & Emotion
  { id: 'grinning_face', emoji: '😀', name: 'Grinning Face', category: EmojiCategory.SMILEYS, keywords: ['smile', 'happy', 'face'], hasSkinTones: false },
  { id: 'beaming_face', emoji: '😁', name: 'Beaming Face with Smiling Eyes', category: EmojiCategory.SMILEYS, keywords: ['smile', 'happy', 'joy'], hasSkinTones: false },
  { id: 'face_with_joy', emoji: '😂', name: 'Face with Tears of Joy', category: EmojiCategory.SMILEYS, keywords: ['laugh', 'happy', 'cry'], hasSkinTones: false },
  { id: 'rolling_on_floor', emoji: '🤣', name: 'Rolling on the Floor Laughing', category: EmojiCategory.SMILEYS, keywords: ['laugh', 'happy', 'floor'], hasSkinTones: false },
  { id: 'smiling_face', emoji: '☺️', name: 'Smiling Face', category: EmojiCategory.SMILEYS, keywords: ['smile', 'happy'], hasSkinTones: false },
  { id: 'sweat_smile', emoji: '😅', name: 'Smiling Face with Sweat', category: EmojiCategory.SMILEYS, keywords: ['smile', 'sweat', 'hot'], hasSkinTones: false },
  { id: 'joy_face', emoji: '😆', name: 'Grinning Face with Smiling Eyes', category: EmojiCategory.SMILEYS, keywords: ['laugh', 'happy', 'joy'], hasSkinTones: false },
  { id: 'winking_face', emoji: '😉', name: 'Winking Face', category: EmojiCategory.SMILEYS, keywords: ['wink', 'smile'], hasSkinTones: false },
  { id: 'smiling_sweat', emoji: '😊', name: 'Smiling Face with Smiling Eyes', category: EmojiCategory.SMILEYS, keywords: ['smile', 'happy', 'joy'], hasSkinTones: false },
  { id: 'innocent_face', emoji: '😇', name: 'Smiling Face with Halo', category: EmojiCategory.SMILEYS, keywords: ['angel', 'halo', 'innocent'], hasSkinTones: false },
  { id: 'heart_eyes', emoji: '😍', name: 'Smiling Face with Heart Eyes', category: EmojiCategory.SMILEYS, keywords: ['love', 'heart', 'happy'], hasSkinTones: false },
  { id: 'star_eyes', emoji: '🤩', name: 'Smiling Face with Star Eyes', category: EmojiCategory.SMILEYS, keywords: ['star', 'eyes', 'love'], hasSkinTones: false },
  { id: 'kissing_heart', emoji: '😘', name: 'Kissing Face with Heart Eyes', category: EmojiCategory.SMILEYS, keywords: ['kiss', 'heart', 'love'], hasSkinTones: false },
  { id: 'thinking', emoji: '🤔', name: 'Thinking Face', category: EmojiCategory.SMILEYS, keywords: ['think', 'puzzle', 'confused'], hasSkinTones: false },
  { id: 'mouth_open', emoji: '😮', name: 'Surprised Face', category: EmojiCategory.SMILEYS, keywords: ['surprise', 'amazed', 'shocked'], hasSkinTones: false },
  { id: 'raised_eyebrow', emoji: '🤨', name: 'Raised Eyebrow', category: EmojiCategory.SMILEYS, keywords: ['doubt', 'skeptical', 'eyebrow'], hasSkinTones: false },
  { id: 'neutral', emoji: '😐', name: 'Neutral Face', category: EmojiCategory.SMILEYS, keywords: ['neutral', 'unimpressed'], hasSkinTones: false },
  { id: 'expressionless', emoji: '😑', name: 'Expressionless Face', category: EmojiCategory.SMILEYS, keywords: ['meh', 'blank', 'unimpressed'], hasSkinTones: false },
  { id: 'confused', emoji: '😕', name: 'Confused Face', category: EmojiCategory.SMILEYS, keywords: ['confused', 'unsure'], hasSkinTones: false },
  { id: 'worried', emoji: '😟', name: 'Worried Face', category: EmojiCategory.SMILEYS, keywords: ['worry', 'scared', 'concerned'], hasSkinTones: false },
  { id: 'angry', emoji: '😠', name: 'Angry Face', category: EmojiCategory.SMILEYS, keywords: ['angry', 'mean', 'face'], hasSkinTones: false },
  { id: 'rage', emoji: '😡', name: 'Pouting Face', category: EmojiCategory.SMILEYS, keywords: ['angry', 'rage', 'hate'], hasSkinTones: false },
  { id: 'crying', emoji: '😢', name: 'Crying Face', category: EmojiCategory.SMILEYS, keywords: ['sad', 'cry', 'tear'], hasSkinTones: false },
  { id: 'sad', emoji: '😞', name: 'Disappointed Face', category: EmojiCategory.SMILEYS, keywords: ['sad', 'disappointed'], hasSkinTones: false },
  { id: 'triumph', emoji: '😤', name: 'Face with Steam from Nose', category: EmojiCategory.SMILEYS, keywords: ['frustration', 'steam'], hasSkinTones: false },
  { id: 'frowning', emoji: '🙁', name: 'Slightly Frowning Face', category: EmojiCategory.SMILEYS, keywords: ['frown', 'sad'], hasSkinTones: false },
  { id: 'anguished', emoji: '😧', name: 'Anguished Face', category: EmojiCategory.SMILEYS, keywords: ['scared', 'shocked'], hasSkinTones: false },
  { id: 'scream', emoji: '😱', name: 'Face Screaming in Fear', category: EmojiCategory.SMILEYS, keywords: ['scary', 'shocked', 'afraid'], hasSkinTones: false },
  { id: 'astonished', emoji: '😲', name: 'Astonished Face', category: EmojiCategory.SMILEYS, keywords: ['surprised', 'shocked', 'amazed'], hasSkinTones: false },
  { id: 'flushed', emoji: '😳', name: 'Flushed Face', category: EmojiCategory.SMILEYS, keywords: ['blush', 'shy', 'embarrassed'], hasSkinTones: false },
  { id: 'sleeping', emoji: '😴', name: 'Sleeping Face', category: EmojiCategory.SMILEYS, keywords: ['sleep', 'tired'], hasSkinTones: false },
  { id: 'dizzy', emoji: '😵', name: 'Dizzy Face', category: EmojiCategory.SMILEYS, keywords: ['dizzy', 'confused'], hasSkinTones: false },
  { id: 'face_with_mask', emoji: '😷', name: 'Face with Medical Mask', category: EmojiCategory.SMILEYS, keywords: ['sick', 'medical', 'mask'], hasSkinTones: false },
  { id: 'grinning_sweat', emoji: '😬', name: 'Grimacing Face', category: EmojiCategory.SMILEYS, keywords: ['grimace', 'awkward'], hasSkinTones: false },
  { id: 'hugging_face', emoji: '🤗', name: 'Hugging Face', category: EmojiCategory.SMILEYS, keywords: ['hug', 'support'], hasSkinTones: false },
  { id: 'thinking_face', emoji: '🤨', name: 'Face with Raised Eyebrow', category: EmojiCategory.SMILEYS, keywords: ['think', 'suspicious'], hasSkinTones: false },
  { id: 'shushing_face', emoji: '🤫', name: 'Shushing Face', category: EmojiCategory.SMILEYS, keywords: ['shush', 'quiet', 'silence'], hasSkinTones: false },
  { id: 'nauseated_face', emoji: '🤢', name: 'Nauseated Face', category: EmojiCategory.SMILEYS, keywords: ['sick', 'puke'], hasSkinTones: false },
  { id: 'sneezing_face', emoji: '🤧', name: 'Sneezing Face', category: EmojiCategory.SMILEYS, keywords: ['sneeze', 'sick'], hasSkinTones: false },
  { id: 'vomiting_face', emoji: '🤮', name: 'Vomiting Face', category: EmojiCategory.SMILEYS, keywords: ['vomit', 'sick'], hasSkinTones: false },
  { id: 'hot_face', emoji: '🥵', name: 'Hot Face', category: EmojiCategory.SMILEYS, keywords: ['hot', 'heat', 'warm'], hasSkinTones: false },
  { id: 'cold_face', emoji: '🥶', name: 'Cold Face', category: EmojiCategory.SMILEYS, keywords: ['cold', 'freezing'], hasSkinTones: false },
  { id: 'weary_face', emoji: '😩', name: 'Weary Face', category: EmojiCategory.SMILEYS, keywords: ['tired', 'exhausted'], hasSkinTones: false },
  { id: 'tired_face', emoji: '😫', name: 'Tired Face', category: EmojiCategory.SMILEYS, keywords: ['tired', 'sleepy'], hasSkinTones: false },

  // People
  { id: 'wave', emoji: '👋', name: 'Waving Hand', category: EmojiCategory.PEOPLE, keywords: ['wave', 'hello', 'goodbye'], hasSkinTones: true, skinToneVariants: applySkinTones('👋') },
  { id: 'raised_back_hand', emoji: '🤚', name: 'Raised Back of Hand', category: EmojiCategory.PEOPLE, keywords: ['hand', 'raised'], hasSkinTones: true, skinToneVariants: applySkinTones('🤚') },
  { id: 'raised_hand', emoji: '✋', name: 'Raised Hand', category: EmojiCategory.PEOPLE, keywords: ['hand', 'raised', 'stop'], hasSkinTones: true, skinToneVariants: applySkinTones('✋') },
  { id: 'vulcan_salute', emoji: '🖖', name: 'Vulcan Salute', category: EmojiCategory.PEOPLE, keywords: ['hand', 'peace'], hasSkinTones: true, skinToneVariants: applySkinTones('🖖') },
  { id: 'ok_hand', emoji: '👌', name: 'OK Hand', category: EmojiCategory.PEOPLE, keywords: ['ok', 'good', 'perfect'], hasSkinTones: true, skinToneVariants: applySkinTones('👌') },
  { id: 'pinching_hand', emoji: '🤏', name: 'Pinching Hand', category: EmojiCategory.PEOPLE, keywords: ['pinch', 'small'], hasSkinTones: true, skinToneVariants: applySkinTones('🤏') },
  { id: 'victory', emoji: '✌️', name: 'Victory Hand', category: EmojiCategory.PEOPLE, keywords: ['peace', 'victory'], hasSkinTones: true, skinToneVariants: applySkinTones('✌️') },
  { id: 'love_you', emoji: '🤟', name: 'I Love You Hand Sign', category: EmojiCategory.PEOPLE, keywords: ['love', 'gesture'], hasSkinTones: true, skinToneVariants: applySkinTones('🤟') },
  { id: 'metal', emoji: '🤘', name: 'Sign of the Horns', category: EmojiCategory.PEOPLE, keywords: ['rock', 'metal', 'horns'], hasSkinTones: true, skinToneVariants: applySkinTones('🤘') },
  { id: 'call_me', emoji: '🤙', name: 'Call Me Hand', category: EmojiCategory.PEOPLE, keywords: ['call', 'phone'], hasSkinTones: true, skinToneVariants: applySkinTones('🤙') },
  { id: 'point_left', emoji: '👈', name: 'Backhand Index Pointing Left', category: EmojiCategory.PEOPLE, keywords: ['point', 'left', 'arrow'], hasSkinTones: true, skinToneVariants: applySkinTones('👈') },
  { id: 'point_right', emoji: '👉', name: 'Backhand Index Pointing Right', category: EmojiCategory.PEOPLE, keywords: ['point', 'right', 'arrow'], hasSkinTones: true, skinToneVariants: applySkinTones('👉') },
  { id: 'point_up_2', emoji: '👆', name: 'Backhand Index Pointing Up', category: EmojiCategory.PEOPLE, keywords: ['point', 'up', 'arrow'], hasSkinTones: true, skinToneVariants: applySkinTones('👆') },
  { id: 'point_down', emoji: '👇', name: 'Backhand Index Pointing Down', category: EmojiCategory.PEOPLE, keywords: ['point', 'down', 'arrow'], hasSkinTones: true, skinToneVariants: applySkinTones('👇') },
  { id: 'point_up', emoji: '☝️', name: 'Index Pointing Up', category: EmojiCategory.PEOPLE, keywords: ['point', 'up', 'arrow'], hasSkinTones: true, skinToneVariants: applySkinTones('☝️') },
  { id: 'thumbsup', emoji: '👍', name: 'Thumbs Up', category: EmojiCategory.PEOPLE, keywords: ['thumbs', 'up', 'good'], hasSkinTones: true, skinToneVariants: applySkinTones('👍') },
  { id: 'thumbsdown', emoji: '👎', name: 'Thumbs Down', category: EmojiCategory.PEOPLE, keywords: ['thumbs', 'down', 'bad'], hasSkinTones: true, skinToneVariants: applySkinTones('👎') },
  { id: 'fist', emoji: '✊', name: 'Raised Fist', category: EmojiCategory.PEOPLE, keywords: ['fist', 'power', 'punch'], hasSkinTones: true, skinToneVariants: applySkinTones('✊') },
  { id: 'facepunch', emoji: '👊', name: 'Oncoming Fist', category: EmojiCategory.PEOPLE, keywords: ['fist', 'punch', 'punch'], hasSkinTones: true, skinToneVariants: applySkinTones('👊') },
  { id: 'handshake', emoji: '🤝', name: 'Handshake', category: EmojiCategory.PEOPLE, keywords: ['hand', 'shake', 'deal'], hasSkinTones: false },
  { id: 'clap', emoji: '👏', name: 'Clapping Hands', category: EmojiCategory.PEOPLE, keywords: ['clap', 'applause'], hasSkinTones: true, skinToneVariants: applySkinTones('👏') },
  { id: 'raised_hands', emoji: '🙌', name: 'Raising Hands', category: EmojiCategory.PEOPLE, keywords: ['celebration', 'party'], hasSkinTones: true, skinToneVariants: applySkinTones('🙌') },
  { id: 'open_hands', emoji: '👐', name: 'Open Hands', category: EmojiCategory.PEOPLE, keywords: ['hands', 'open'], hasSkinTones: true, skinToneVariants: applySkinTones('👐') },
  { id: 'palms_up', emoji: '🤲', name: 'Open Hands with Fingers Splayed', category: EmojiCategory.PEOPLE, keywords: ['hands', 'palms'], hasSkinTones: true, skinToneVariants: applySkinTones('🤲') },
  { id: 'handwriting', emoji: '👋', name: 'Writing Hand', category: EmojiCategory.PEOPLE, keywords: ['write', 'hand'], hasSkinTones: true, skinToneVariants: applySkinTones('👋') },
  { id: 'nail_care', emoji: '💅', name: 'Nail Polish', category: EmojiCategory.PEOPLE, keywords: ['nails', 'beauty'], hasSkinTones: true, skinToneVariants: applySkinTones('💅') },
  { id: 'lips', emoji: '👄', name: 'Lips', category: EmojiCategory.PEOPLE, keywords: ['mouth', 'kiss'], hasSkinTones: false },
  { id: 'tooth', emoji: '👦', name: 'Boy', category: EmojiCategory.PEOPLE, keywords: ['boy', 'child'], hasSkinTones: true, skinToneVariants: applySkinTones('👦') },

  // Nature
  { id: 'dog', emoji: '🐶', name: 'Dog Face', category: EmojiCategory.NATURE, keywords: ['dog', 'pet', 'woof'], hasSkinTones: false },
  { id: 'cat', emoji: '🐱', name: 'Cat Face', category: EmojiCategory.NATURE, keywords: ['cat', 'pet', 'meow'], hasSkinTones: false },
  { id: 'monkey', emoji: '🐵', name: 'Monkey Face', category: EmojiCategory.NATURE, keywords: ['monkey', 'animal'], hasSkinTones: false },
  { id: 'chicken', emoji: '🐔', name: 'Chicken', category: EmojiCategory.NATURE, keywords: ['chicken', 'bird'], hasSkinTones: false },
  { id: 'penguin', emoji: '🐧', name: 'Penguin', category: EmojiCategory.NATURE, keywords: ['penguin', 'bird'], hasSkinTones: false },
  { id: 'fish', emoji: '🐟', name: 'Fish', category: EmojiCategory.NATURE, keywords: ['fish', 'water', 'animal'], hasSkinTones: false },
  { id: 'butterfly', emoji: '🦋', name: 'Butterfly', category: EmojiCategory.NATURE, keywords: ['butterfly', 'insect', 'nature'], hasSkinTones: false },
  { id: 'flower', emoji: '🌸', name: 'Cherry Blossom', category: EmojiCategory.NATURE, keywords: ['flower', 'spring'], hasSkinTones: false },
  { id: 'sunflower', emoji: '🌻', name: 'Sunflower', category: EmojiCategory.NATURE, keywords: ['sunflower', 'flower', 'nature'], hasSkinTones: false },
  { id: 'rose', emoji: '🌹', name: 'Rose', category: EmojiCategory.NATURE, keywords: ['rose', 'flower', 'love'], hasSkinTones: false },
  { id: 'hibiscus', emoji: '🌺', name: 'Hibiscus', category: EmojiCategory.NATURE, keywords: ['flower', 'hibiscus'], hasSkinTones: false },
  { id: 'tree', emoji: '🌳', name: 'Deciduous Tree', category: EmojiCategory.NATURE, keywords: ['tree', 'nature'], hasSkinTones: false },
  { id: 'evergreen_tree', emoji: '🌲', name: 'Evergreen Tree', category: EmojiCategory.NATURE, keywords: ['tree', 'nature'], hasSkinTones: false },
  { id: 'palm_tree', emoji: '🌴', name: 'Palm Tree', category: EmojiCategory.NATURE, keywords: ['palm', 'tree', 'beach'], hasSkinTones: false },

  // Food & Drink
  { id: 'apple', emoji: '🍎', name: 'Red Apple', category: EmojiCategory.FOOD, keywords: ['apple', 'fruit', 'red'], hasSkinTones: false },
  { id: 'banana', emoji: '🍌', name: 'Banana', category: EmojiCategory.FOOD, keywords: ['banana', 'fruit', 'yellow'], hasSkinTones: false },
  { id: 'orange', emoji: '🍊', name: 'Orange', category: EmojiCategory.FOOD, keywords: ['orange', 'fruit', 'citrus'], hasSkinTones: false },
  { id: 'lemon', emoji: '🍋', name: 'Lemon', category: EmojiCategory.FOOD, keywords: ['lemon', 'fruit', 'citrus'], hasSkinTones: false },
  { id: 'strawberry', emoji: '🍓', name: 'Strawberry', category: EmojiCategory.FOOD, keywords: ['strawberry', 'fruit', 'red'], hasSkinTones: false },
  { id: 'grapes', emoji: '🍇', name: 'Grapes', category: EmojiCategory.FOOD, keywords: ['grapes', 'fruit', 'wine'], hasSkinTones: false },
  { id: 'watermelon', emoji: '🍉', name: 'Watermelon', category: EmojiCategory.FOOD, keywords: ['watermelon', 'fruit', 'summer'], hasSkinTones: false },
  { id: 'bread', emoji: '🍞', name: 'Bread', category: EmojiCategory.FOOD, keywords: ['bread', 'bake'], hasSkinTones: false },
  { id: 'pizza', emoji: '🍕', name: 'Pizza', category: EmojiCategory.FOOD, keywords: ['pizza', 'food', 'italian'], hasSkinTones: false },
  { id: 'hamburger', emoji: '🍔', name: 'Hamburger', category: EmojiCategory.FOOD, keywords: ['hamburger', 'food', 'burger'], hasSkinTones: false },
  { id: 'fries', emoji: '🍟', name: 'French Fries', category: EmojiCategory.FOOD, keywords: ['fries', 'food'], hasSkinTones: false },
  { id: 'popcorn', emoji: '🍿', name: 'Popcorn', category: EmojiCategory.FOOD, keywords: ['popcorn', 'food', 'movie'], hasSkinTones: false },
  { id: 'cake', emoji: '🍰', name: 'Cake', category: EmojiCategory.FOOD, keywords: ['cake', 'dessert'], hasSkinTones: false },
  { id: 'ice_cream', emoji: '🍦', name: 'Soft Ice Cream', category: EmojiCategory.FOOD, keywords: ['ice cream', 'dessert'], hasSkinTones: false },
  { id: 'coffee', emoji: '☕', name: 'Hot Beverage', category: EmojiCategory.FOOD, keywords: ['coffee', 'tea', 'hot'], hasSkinTones: false },
  { id: 'beer', emoji: '🍺', name: 'Beer Mug', category: EmojiCategory.FOOD, keywords: ['beer', 'alcohol'], hasSkinTones: false },
  { id: 'wine_glass', emoji: '🍷', name: 'Wine Glass', category: EmojiCategory.FOOD, keywords: ['wine', 'alcohol'], hasSkinTones: false },

  // Travel & Places
  { id: 'airplane', emoji: '✈️', name: 'Airplane', category: EmojiCategory.TRAVEL, keywords: ['airplane', 'travel', 'flight'], hasSkinTones: false },
  { id: 'rocket', emoji: '🚀', name: 'Rocket', category: EmojiCategory.TRAVEL, keywords: ['rocket', 'space', 'launch'], hasSkinTones: false },
  { id: 'car', emoji: '🚗', name: 'Automobile', category: EmojiCategory.TRAVEL, keywords: ['car', 'vehicle'], hasSkinTones: false },
  { id: 'train', emoji: '🚂', name: 'Locomotive', category: EmojiCategory.TRAVEL, keywords: ['train', 'travel'], hasSkinTones: false },
  { id: 'ship', emoji: '⛴️', name: 'Ferry', category: EmojiCategory.TRAVEL, keywords: ['ship', 'boat', 'travel'], hasSkinTones: false },
  { id: 'world_map', emoji: '🗺️', name: 'World Map', category: EmojiCategory.TRAVEL, keywords: ['map', 'world'], hasSkinTones: false },
  { id: 'mountain', emoji: '⛰️', name: 'Mountain', category: EmojiCategory.TRAVEL, keywords: ['mountain', 'nature'], hasSkinTones: false },
  { id: 'beach', emoji: '🏖️', name: 'Beach with Umbrella', category: EmojiCategory.TRAVEL, keywords: ['beach', 'sand', 'vacation'], hasSkinTones: false },
  { id: 'sunrise', emoji: '🌅', name: 'Sunrise', category: EmojiCategory.TRAVEL, keywords: ['sunrise', 'morning'], hasSkinTones: false },
  { id: 'sunset', emoji: '🌇', name: 'Sunset', category: EmojiCategory.TRAVEL, keywords: ['sunset', 'evening'], hasSkinTones: false },
  { id: 'rainbow', emoji: '🌈', name: 'Rainbow', category: EmojiCategory.TRAVEL, keywords: ['rainbow', 'weather'], hasSkinTones: false },
  { id: 'house', emoji: '🏠', name: 'House', category: EmojiCategory.TRAVEL, keywords: ['house', 'home', 'building'], hasSkinTones: false },
  { id: 'office_building', emoji: '🏢', name: 'Office Building', category: EmojiCategory.TRAVEL, keywords: ['office', 'building'], hasSkinTones: false },
  { id: 'statue_of_liberty', emoji: '🗽', name: 'Statue of Liberty', category: EmojiCategory.TRAVEL, keywords: ['statue', 'liberty'], hasSkinTones: false },

  // Activities
  { id: 'soccer', emoji: '⚽', name: 'Soccer Ball', category: EmojiCategory.ACTIVITIES, keywords: ['soccer', 'football', 'sports'], hasSkinTones: false },
  { id: 'basketball', emoji: '🏀', name: 'Basketball', category: EmojiCategory.ACTIVITIES, keywords: ['basketball', 'sports'], hasSkinTones: false },
  { id: 'baseball', emoji: '⚾', name: 'Baseball', category: EmojiCategory.ACTIVITIES, keywords: ['baseball', 'sports'], hasSkinTones: false },
  { id: 'american_football', emoji: '🏈', name: 'American Football', category: EmojiCategory.ACTIVITIES, keywords: ['football', 'sports'], hasSkinTones: false },
  { id: 'tennis', emoji: '🎾', name: 'Tennis', category: EmojiCategory.ACTIVITIES, keywords: ['tennis', 'sports'], hasSkinTones: false },
  { id: 'bowling', emoji: '🎳', name: 'Bowling', category: EmojiCategory.ACTIVITIES, keywords: ['bowling', 'sports'], hasSkinTones: false },
  { id: 'video_game', emoji: '🎮', name: 'Video Game', category: EmojiCategory.ACTIVITIES, keywords: ['game', 'gaming'], hasSkinTones: false },
  { id: 'guitar', emoji: '🎸', name: 'Guitar', category: EmojiCategory.ACTIVITIES, keywords: ['guitar', 'music'], hasSkinTones: false },
  { id: 'musical_note', emoji: '🎵', name: 'Musical Note', category: EmojiCategory.ACTIVITIES, keywords: ['music', 'note'], hasSkinTones: false },
  { id: 'microphone', emoji: '🎤', name: 'Microphone', category: EmojiCategory.ACTIVITIES, keywords: ['microphone', 'sing'], hasSkinTones: false },

  // Objects
  { id: 'watch', emoji: '⌚', name: 'Watch', category: EmojiCategory.OBJECTS, keywords: ['watch', 'time'], hasSkinTones: false },
  { id: 'iphone', emoji: '📱', name: 'Mobile Phone', category: EmojiCategory.OBJECTS, keywords: ['phone', 'mobile'], hasSkinTones: false },
  { id: 'computer', emoji: '💻', name: 'Laptop', category: EmojiCategory.OBJECTS, keywords: ['computer', 'laptop'], hasSkinTones: false },
  { id: 'keyboard', emoji: '⌨️', name: 'Keyboard', category: EmojiCategory.OBJECTS, keywords: ['keyboard', 'type'], hasSkinTones: false },
  { id: 'mouse', emoji: '🖱️', name: 'Computer Mouse', category: EmojiCategory.OBJECTS, keywords: ['mouse', 'computer'], hasSkinTones: false },
  { id: 'camera', emoji: '📷', name: 'Camera', category: EmojiCategory.OBJECTS, keywords: ['camera', 'photo'], hasSkinTones: false },
  { id: 'movie_camera', emoji: '🎥', name: 'Movie Camera', category: EmojiCategory.OBJECTS, keywords: ['camera', 'movie', 'video'], hasSkinTones: false },
  { id: 'television', emoji: '📺', name: 'Television', category: EmojiCategory.OBJECTS, keywords: ['tv', 'television'], hasSkinTones: false },
  { id: 'radio', emoji: '📻', name: 'Radio', category: EmojiCategory.OBJECTS, keywords: ['radio', 'broadcast'], hasSkinTones: false },
  { id: 'headphones', emoji: '🎧', name: 'Headphone', category: EmojiCategory.OBJECTS, keywords: ['headphones', 'music'], hasSkinTones: false },
  { id: 'briefcase', emoji: '💼', name: 'Briefcase', category: EmojiCategory.OBJECTS, keywords: ['briefcase', 'work'], hasSkinTones: false },
  { id: 'book', emoji: '📖', name: 'Open Book', category: EmojiCategory.OBJECTS, keywords: ['book', 'read'], hasSkinTones: false },
  { id: 'newspaper', emoji: '📰', name: 'Newspaper', category: EmojiCategory.OBJECTS, keywords: ['newspaper', 'news'], hasSkinTones: false },
  { id: 'gift', emoji: '🎁', name: 'Wrapped Gift', category: EmojiCategory.OBJECTS, keywords: ['gift', 'present'], hasSkinTones: false },
  { id: 'alarm_clock', emoji: '⏰', name: 'Alarm Clock', category: EmojiCategory.OBJECTS, keywords: ['alarm', 'clock', 'time'], hasSkinTones: false },
  { id: 'hourglass', emoji: '⌛', name: 'Hourglass Done', category: EmojiCategory.OBJECTS, keywords: ['hourglass', 'time'], hasSkinTones: false },
  { id: 'bulb', emoji: '💡', name: 'Light Bulb', category: EmojiCategory.OBJECTS, keywords: ['light', 'bulb', 'idea'], hasSkinTones: false },
  { id: 'flashlight', emoji: '🔦', name: 'Flashlight', category: EmojiCategory.OBJECTS, keywords: ['flashlight', 'light'], hasSkinTones: false },
  { id: 'candle', emoji: '🕯️', name: 'Candle', category: EmojiCategory.OBJECTS, keywords: ['candle', 'light'], hasSkinTones: false },
  { id: 'lock', emoji: '🔒', name: 'Locked', category: EmojiCategory.OBJECTS, keywords: ['lock', 'secure'], hasSkinTones: false },
  { id: 'key', emoji: '🔑', name: 'Key', category: EmojiCategory.OBJECTS, keywords: ['key', 'access'], hasSkinTones: false },
  { id: 'hammer', emoji: '🔨', name: 'Hammer', category: EmojiCategory.OBJECTS, keywords: ['hammer', 'tool'], hasSkinTones: false },
  { id: 'gun', emoji: '🔫', name: 'Pistol', category: EmojiCategory.OBJECTS, keywords: ['gun', 'weapon'], hasSkinTones: false },
  { id: 'axe', emoji: '🪓', name: 'Axe', category: EmojiCategory.OBJECTS, keywords: ['axe', 'tool'], hasSkinTones: false },

  // Symbols
  { id: 'heart', emoji: '❤️', name: 'Red Heart', category: EmojiCategory.SYMBOLS, keywords: ['heart', 'love', 'red'], hasSkinTones: false },
  { id: 'orange_heart', emoji: '🧡', name: 'Orange Heart', category: EmojiCategory.SYMBOLS, keywords: ['heart', 'love', 'orange'], hasSkinTones: false },
  { id: 'yellow_heart', emoji: '💛', name: 'Yellow Heart', category: EmojiCategory.SYMBOLS, keywords: ['heart', 'love', 'yellow'], hasSkinTones: false },
  { id: 'green_heart', emoji: '💚', name: 'Green Heart', category: EmojiCategory.SYMBOLS, keywords: ['heart', 'love', 'green'], hasSkinTones: false },
  { id: 'blue_heart', emoji: '💙', name: 'Blue Heart', category: EmojiCategory.SYMBOLS, keywords: ['heart', 'love', 'blue'], hasSkinTones: false },
  { id: 'purple_heart', emoji: '💜', name: 'Purple Heart', category: EmojiCategory.SYMBOLS, keywords: ['heart', 'love', 'purple'], hasSkinTones: false },
  { id: 'black_heart', emoji: '🖤', name: 'Black Heart', category: EmojiCategory.SYMBOLS, keywords: ['heart', 'black'], hasSkinTones: false },
  { id: 'white_heart', emoji: '🤍', name: 'White Heart', category: EmojiCategory.SYMBOLS, keywords: ['heart', 'white'], hasSkinTones: false },
  { id: 'broken_heart', emoji: '💔', name: 'Broken Heart', category: EmojiCategory.SYMBOLS, keywords: ['heart', 'sad', 'broken'], hasSkinTones: false },
  { id: 'star', emoji: '⭐', name: 'Star', category: EmojiCategory.SYMBOLS, keywords: ['star', 'favorite'], hasSkinTones: false },
  { id: 'sun', emoji: '☀️', name: 'Sun', category: EmojiCategory.SYMBOLS, keywords: ['sun', 'weather'], hasSkinTones: false },
  { id: 'moon', emoji: '🌙', name: 'Crescent Moon', category: EmojiCategory.SYMBOLS, keywords: ['moon', 'night'], hasSkinTones: false },
  { id: 'fire', emoji: '🔥', name: 'Fire', category: EmojiCategory.SYMBOLS, keywords: ['fire', 'hot', 'flame'], hasSkinTones: false },
  { id: 'sparkles', emoji: '✨', name: 'Sparkles', category: EmojiCategory.SYMBOLS, keywords: ['sparkles', 'glitter'], hasSkinTones: false },
  { id: 'snowflake', emoji: '❄️', name: 'Snowflake', category: EmojiCategory.SYMBOLS, keywords: ['snowflake', 'cold', 'winter'], hasSkinTones: false },
  { id: 'check_mark', emoji: '✅', name: 'Check Mark Button', category: EmojiCategory.SYMBOLS, keywords: ['check', 'mark', 'ok'], hasSkinTones: false },
  { id: 'x', emoji: '❌', name: 'Cross Mark', category: EmojiCategory.SYMBOLS, keywords: ['cross', 'mark', 'wrong'], hasSkinTones: false },
  { id: 'warning', emoji: '⚠️', name: 'Warning', category: EmojiCategory.SYMBOLS, keywords: ['warning', 'alert'], hasSkinTones: false },
  { id: 'forbidden', emoji: '🚫', name: 'Prohibited', category: EmojiCategory.SYMBOLS, keywords: ['forbidden', 'no'], hasSkinTones: false },
  { id: 'question_mark', emoji: '❓', name: 'Red Question Mark', category: EmojiCategory.SYMBOLS, keywords: ['question', 'mark', 'help'], hasSkinTones: false },
  { id: 'grey_question_mark', emoji: '❔', name: 'White Question Mark', category: EmojiCategory.SYMBOLS, keywords: ['question', 'mark'], hasSkinTones: false },
  { id: 'exclamation', emoji: '❕', name: 'White Exclamation Mark', category: EmojiCategory.SYMBOLS, keywords: ['exclamation', 'mark'], hasSkinTones: false },
  { id: 'heavy_exclamation_mark', emoji: '❗', name: 'Heavy Exclamation Mark Symbol', category: EmojiCategory.SYMBOLS, keywords: ['exclamation', 'mark'], hasSkinTones: false },
  { id: 'hundred_points', emoji: '💯', name: 'Hundred Points', category: EmojiCategory.SYMBOLS, keywords: ['100', 'score'], hasSkinTones: false },
  { id: 'zzz', emoji: '💤', name: 'Zzz', category: EmojiCategory.SYMBOLS, keywords: ['sleep', 'zzz'], hasSkinTones: false },

  // Medieval & Fantasy
  { id: 'med_swords',    emoji: '⚔️', name: 'Crossed Swords',     category: EmojiCategory.MEDIEVAL, keywords: ['sword','battle','fight','medieval'],          hasSkinTones: false },
  { id: 'med_dagger',   emoji: '🗡️', name: 'Dagger',             category: EmojiCategory.MEDIEVAL, keywords: ['knife','stab','weapon','assassin'],           hasSkinTones: false },
  { id: 'med_shield',   emoji: '🛡️', name: 'Shield',             category: EmojiCategory.MEDIEVAL, keywords: ['defense','armor','protect','knight'],          hasSkinTones: false },
  { id: 'med_castle',   emoji: '🏰', name: 'Castle',             category: EmojiCategory.MEDIEVAL, keywords: ['fortress','kingdom','king','medieval'],         hasSkinTones: false },
  { id: 'med_crown',    emoji: '👑', name: 'Crown',              category: EmojiCategory.MEDIEVAL, keywords: ['royalty','king','queen','gold'],                hasSkinTones: false },
  { id: 'med_prince',   emoji: '🤴', name: 'Prince',             category: EmojiCategory.MEDIEVAL, keywords: ['royal','knight','heir','medieval'],             hasSkinTones: true,  skinToneVariants: applySkinTones('🤴') },
  { id: 'med_princess', emoji: '👸', name: 'Princess',           category: EmojiCategory.MEDIEVAL, keywords: ['royal','girl','heir','tower'],                  hasSkinTones: true,  skinToneVariants: applySkinTones('👸') },
  { id: 'med_wizard',   emoji: '🧙', name: 'Wizard',             category: EmojiCategory.MEDIEVAL, keywords: ['mage','sorcerer','magic','spell'],              hasSkinTones: true,  skinToneVariants: applySkinTones('🧙') },
  { id: 'med_elf',      emoji: '🧝', name: 'Elf',               category: EmojiCategory.MEDIEVAL, keywords: ['archer','fantasy','tolkien','forest'],          hasSkinTones: true,  skinToneVariants: applySkinTones('🧝') },
  { id: 'med_vampire',  emoji: '🧛', name: 'Vampire',            category: EmojiCategory.MEDIEVAL, keywords: ['blood','bat','immortal','fangs'],               hasSkinTones: true,  skinToneVariants: applySkinTones('🧛') },
  { id: 'med_zombie',   emoji: '🧟', name: 'Zombie',             category: EmojiCategory.MEDIEVAL, keywords: ['undead','brains','shuffle','horror'],           hasSkinTones: true,  skinToneVariants: applySkinTones('🧟') },
  { id: 'med_genie',    emoji: '🧞', name: 'Genie',              category: EmojiCategory.MEDIEVAL, keywords: ['wish','lamp','magic','djinn'],                  hasSkinTones: true,  skinToneVariants: applySkinTones('🧞') },
  { id: 'med_unicorn',  emoji: '🦄', name: 'Unicorn',            category: EmojiCategory.MEDIEVAL, keywords: ['magic','horse','horn','rainbow'],               hasSkinTones: false },
  { id: 'med_dragon',   emoji: '🐉', name: 'Dragon',             category: EmojiCategory.MEDIEVAL, keywords: ['fire','beast','fantasy','scales'],              hasSkinTones: false },
  { id: 'med_bow',      emoji: '🏹', name: 'Bow and Arrow',      category: EmojiCategory.MEDIEVAL, keywords: ['archer','shoot','hunt','aim'],                  hasSkinTones: false },
  { id: 'med_wand',     emoji: '🪄', name: 'Magic Wand',         category: EmojiCategory.MEDIEVAL, keywords: ['spell','magic','trick','abracadabra'],          hasSkinTones: false },
  { id: 'med_crystal',  emoji: '🔮', name: 'Crystal Ball',       category: EmojiCategory.MEDIEVAL, keywords: ['fortune','predict','mystic','oracle'],          hasSkinTones: false },
  { id: 'med_scroll',   emoji: '📜', name: 'Scroll',             category: EmojiCategory.MEDIEVAL, keywords: ['parchment','spell','ancient','map'],            hasSkinTones: false },
  { id: 'med_candle',   emoji: '🕯️', name: 'Candle',            category: EmojiCategory.MEDIEVAL, keywords: ['fire','dark','ritual','light'],                 hasSkinTones: false },
  { id: 'med_key',      emoji: '🗝️', name: 'Old Key',           category: EmojiCategory.MEDIEVAL, keywords: ['ancient','lock','secret','dungeon'],            hasSkinTones: false },
  { id: 'med_alembic',  emoji: '⚗️', name: 'Alembic',           category: EmojiCategory.MEDIEVAL, keywords: ['potion','brew','alchemy','flask'],              hasSkinTones: false },
  { id: 'med_coin',     emoji: '🪙', name: 'Coin',               category: EmojiCategory.MEDIEVAL, keywords: ['gold','treasure','wealth','merchant'],          hasSkinTones: false },
  { id: 'med_scales',   emoji: '⚖️', name: 'Balance Scale',      category: EmojiCategory.MEDIEVAL, keywords: ['justice','law','fair','judge'],                 hasSkinTones: false },
  { id: 'med_blood',    emoji: '🩸', name: 'Drop of Blood',      category: EmojiCategory.MEDIEVAL, keywords: ['sacrifice','dark','wound','vampire'],           hasSkinTones: false },
  { id: 'med_trident',  emoji: '🔱', name: 'Trident',            category: EmojiCategory.MEDIEVAL, keywords: ['poseidon','sea','power','neptune'],             hasSkinTones: false },

  // 420
  { id: 'herb_herb',    emoji: '🌿', name: 'Herb',               category: EmojiCategory.HERB, keywords: ['plant','green','nature','leaf'],                hasSkinTones: false },
  { id: 'herb_leaves',  emoji: '🍃', name: 'Leaf Fluttering',    category: EmojiCategory.HERB, keywords: ['breeze','nature','plant','blow'],               hasSkinTones: false },
  { id: 'herb_seedling',emoji: '🌱', name: 'Seedling',           category: EmojiCategory.HERB, keywords: ['grow','plant','sprout','garden'],               hasSkinTones: false },
  { id: 'herb_tree',    emoji: '🌲', name: 'Evergreen Tree',      category: EmojiCategory.HERB, keywords: ['pine','forest','tall','green'],                 hasSkinTones: false },
  { id: 'herb_pot',     emoji: '🪴', name: 'Potted Plant',        category: EmojiCategory.HERB, keywords: ['indoor','grow','home','plant'],                 hasSkinTones: false },
  { id: 'herb_smoke',   emoji: '💨', name: 'Dashing Away',        category: EmojiCategory.HERB, keywords: ['blow','wind','exhale','puff'],                  hasSkinTones: false },
  { id: 'herb_fire',    emoji: '🔥', name: 'Fire',               category: EmojiCategory.HERB, keywords: ['hot','burn','flame','light'],                   hasSkinTones: false },
  { id: 'herb_exhale',  emoji: '😮‍💨', name: 'Face Exhaling',    category: EmojiCategory.HERB, keywords: ['breathe','blow','sigh','exhale'],              hasSkinTones: false },
  { id: 'herb_chill',   emoji: '😌', name: 'Relieved Face',       category: EmojiCategory.HERB, keywords: ['calm','chill','relax','peaceful'],              hasSkinTones: false },
  { id: 'herb_hungry',  emoji: '🤤', name: 'Drooling Face',       category: EmojiCategory.HERB, keywords: ['hungry','munchies','want','drool'],             hasSkinTones: false },
  { id: 'herb_pizza',   emoji: '🍕', name: 'Pizza',              category: EmojiCategory.HERB, keywords: ['food','cheese','slice','munchies'],             hasSkinTones: false },
  { id: 'herb_burger',  emoji: '🍔', name: 'Hamburger',           category: EmojiCategory.HERB, keywords: ['food','meat','munchies','burger'],              hasSkinTones: false },
  { id: 'herb_fries',   emoji: '🍟', name: 'French Fries',        category: EmojiCategory.HERB, keywords: ['food','snack','potato','munchies'],             hasSkinTones: false },
  { id: 'herb_cookie',  emoji: '🍪', name: 'Cookie',             category: EmojiCategory.HERB, keywords: ['sweet','snack','bake','edible'],                hasSkinTones: false },
  { id: 'herb_cupcake', emoji: '🧁', name: 'Cupcake',            category: EmojiCategory.HERB, keywords: ['sweet','dessert','bake','edible'],              hasSkinTones: false },
  { id: 'herb_choc',    emoji: '🍫', name: 'Chocolate Bar',       category: EmojiCategory.HERB, keywords: ['sweet','cocoa','dark','edible'],                hasSkinTones: false },
  { id: 'herb_sleep',   emoji: '😴', name: 'Sleeping Face',       category: EmojiCategory.HERB, keywords: ['tired','rest','zzz','couch lock'],              hasSkinTones: false },
  { id: 'herb_thought', emoji: '💭', name: 'Thought Balloon',     category: EmojiCategory.HERB, keywords: ['think','daydream','idea','cloud'],              hasSkinTones: false },
  { id: 'herb_rainbow', emoji: '🌈', name: 'Rainbow',            category: EmojiCategory.HERB, keywords: ['color','sky','hope','vibe'],                    hasSkinTones: false },
  { id: 'herb_peace',   emoji: '☮️', name: 'Peace Symbol',        category: EmojiCategory.HERB, keywords: ['peaceful','harmony','hippy','chill'],           hasSkinTones: false },
  { id: 'herb_zen',     emoji: '🧘', name: 'Person in Lotus',     category: EmojiCategory.HERB, keywords: ['calm','zen','yoga','meditate'],                 hasSkinTones: true, skinToneVariants: applySkinTones('🧘') },
  { id: 'herb_heart',   emoji: '💚', name: 'Green Heart',         category: EmojiCategory.HERB, keywords: ['green','love','nature','420'],                  hasSkinTones: false },
  { id: 'herb_sun',     emoji: '🌻', name: 'Sunflower',           category: EmojiCategory.HERB, keywords: ['sun','flower','yellow','grow'],                 hasSkinTones: false },
  { id: 'herb_couch',   emoji: '🛋️', name: 'Couch',             category: EmojiCategory.HERB, keywords: ['relax','sit','chill','couch lock'],             hasSkinTones: false },
  { id: 'herb_moon',    emoji: '🌙', name: 'Crescent Moon',       category: EmojiCategory.HERB, keywords: ['night','chill','luna','late'],                  hasSkinTones: false },

  // Sci-Fi
  { id: 'sci_ufo',      emoji: '🛸', name: 'Flying Saucer',       category: EmojiCategory.SCIFI, keywords: ['alien','space','ufo','abduct'],                hasSkinTones: false },
  { id: 'sci_rocket',   emoji: '🚀', name: 'Rocket',              category: EmojiCategory.SCIFI, keywords: ['launch','space','travel','nasa'],              hasSkinTones: false },
  { id: 'sci_invader',  emoji: '👾', name: 'Alien Monster',       category: EmojiCategory.SCIFI, keywords: ['game','space','invader','pixel'],              hasSkinTones: false },
  { id: 'sci_alien',    emoji: '👽', name: 'Alien',               category: EmojiCategory.SCIFI, keywords: ['extraterrestrial','space','ufo','green'],      hasSkinTones: false },
  { id: 'sci_robot',    emoji: '🤖', name: 'Robot',               category: EmojiCategory.SCIFI, keywords: ['android','machine','ai','beep'],               hasSkinTones: false },
  { id: 'sci_galaxy',   emoji: '🌌', name: 'Milky Way',           category: EmojiCategory.SCIFI, keywords: ['space','stars','cosmos','universe'],           hasSkinTones: false },
  { id: 'sci_planet',   emoji: '🪐', name: 'Ringed Planet',       category: EmojiCategory.SCIFI, keywords: ['saturn','orbit','space','ring'],               hasSkinTones: false },
  { id: 'sci_comet',    emoji: '☄️', name: 'Comet',              category: EmojiCategory.SCIFI, keywords: ['meteor','space','crash','tail'],               hasSkinTones: false },
  { id: 'sci_star',     emoji: '🌠', name: 'Shooting Star',       category: EmojiCategory.SCIFI, keywords: ['wish','night','meteor','streak'],              hasSkinTones: false },
  { id: 'sci_scope',    emoji: '🔭', name: 'Telescope',           category: EmojiCategory.SCIFI, keywords: ['observe','star','gaze','astronomy'],           hasSkinTones: false },
  { id: 'sci_sat',      emoji: '🛰️', name: 'Satellite',          category: EmojiCategory.SCIFI, keywords: ['orbit','signal','space','dish'],               hasSkinTones: false },
  { id: 'sci_antenna',  emoji: '📡', name: 'Satellite Antenna',   category: EmojiCategory.SCIFI, keywords: ['signal','beam','transmit','contact'],          hasSkinTones: false },
  { id: 'sci_dna',      emoji: '🧬', name: 'DNA',                 category: EmojiCategory.SCIFI, keywords: ['genetics','biology','helix','gene'],           hasSkinTones: false },
  { id: 'sci_atom',     emoji: '⚛️', name: 'Atom Symbol',         category: EmojiCategory.SCIFI, keywords: ['nuclear','physics','science','electron'],      hasSkinTones: false },
  { id: 'sci_cyborg',   emoji: '🦾', name: 'Mechanical Arm',      category: EmojiCategory.SCIFI, keywords: ['cyborg','robot','enhance','prosthetic'],       hasSkinTones: false },
  { id: 'sci_mindblown',emoji: '🤯', name: 'Exploding Head',      category: EmojiCategory.SCIFI, keywords: ['shock','wow','mind','blown'],                  hasSkinTones: false },
  { id: 'sci_scope2',   emoji: '🔬', name: 'Microscope',          category: EmojiCategory.SCIFI, keywords: ['science','lab','tiny','examine'],              hasSkinTones: false },
  { id: 'sci_boom',     emoji: '💥', name: 'Collision',           category: EmojiCategory.SCIFI, keywords: ['boom','blast','impact','explode'],             hasSkinTones: false },
  { id: 'sci_power',    emoji: '⚡', name: 'Lightning',           category: EmojiCategory.SCIFI, keywords: ['power','electric','energy','zap'],             hasSkinTones: false },
  { id: 'sci_portal',   emoji: '🌀', name: 'Cyclone',             category: EmojiCategory.SCIFI, keywords: ['spin','warp','vortex','portal'],               hasSkinTones: false },
  { id: 'sci_void',     emoji: '🕳️', name: 'Black Hole',         category: EmojiCategory.SCIFI, keywords: ['void','gravity','absorb','singularity'],       hasSkinTones: false },
  { id: 'sci_net',      emoji: '🌐', name: 'Globe with Meridians',category: EmojiCategory.SCIFI, keywords: ['internet','world','connect','network'],         hasSkinTones: false },
  { id: 'sci_disk',     emoji: '💾', name: 'Floppy Disk',         category: EmojiCategory.SCIFI, keywords: ['data','save','retro','storage'],               hasSkinTones: false },
  { id: 'sci_battery',  emoji: '🔋', name: 'Battery',             category: EmojiCategory.SCIFI, keywords: ['power','charge','energy','life'],              hasSkinTones: false },
  { id: 'sci_tube',     emoji: '🧪', name: 'Test Tube',           category: EmojiCategory.SCIFI, keywords: ['lab','experiment','science','chemistry'],       hasSkinTones: false },

  // Horror
  { id: 'hor_ghost',    emoji: '👻', name: 'Ghost',               category: EmojiCategory.HORROR, keywords: ['spooky','boo','haunt','spirit'],              hasSkinTones: false },
  { id: 'hor_skull',    emoji: '💀', name: 'Skull',               category: EmojiCategory.HORROR, keywords: ['death','dead','bones','grim'],                hasSkinTones: false },
  { id: 'hor_bones',    emoji: '☠️', name: 'Skull and Crossbones',category: EmojiCategory.HORROR, keywords: ['danger','poison','death','pirate'],           hasSkinTones: false },
  { id: 'hor_zombie',   emoji: '🧟', name: 'Zombie',              category: EmojiCategory.HORROR, keywords: ['undead','brains','shuffle','apocalypse'],     hasSkinTones: true, skinToneVariants: applySkinTones('🧟') },
  { id: 'hor_vamp',     emoji: '🧛', name: 'Vampire',             category: EmojiCategory.HORROR, keywords: ['blood','bite','immortal','fangs'],            hasSkinTones: true, skinToneVariants: applySkinTones('🧛') },
  { id: 'hor_spider',   emoji: '🕷️', name: 'Spider',             category: EmojiCategory.HORROR, keywords: ['creepy','legs','web','arachnid'],             hasSkinTones: false },
  { id: 'hor_web',      emoji: '🕸️', name: 'Spider Web',         category: EmojiCategory.HORROR, keywords: ['trap','sticky','creepy','caught'],            hasSkinTones: false },
  { id: 'hor_bat',      emoji: '🦇', name: 'Bat',                category: EmojiCategory.HORROR, keywords: ['vampire','night','cave','blind'],             hasSkinTones: false },
  { id: 'hor_grave',    emoji: '🪦', name: 'Headstone',           category: EmojiCategory.HORROR, keywords: ['cemetery','rip','death','burial'],            hasSkinTones: false },
  { id: 'hor_coffin',   emoji: '⚰️', name: 'Coffin',             category: EmojiCategory.HORROR, keywords: ['burial','vampire','death','funeral'],         hasSkinTones: false },
  { id: 'hor_blood',    emoji: '🩸', name: 'Drop of Blood',       category: EmojiCategory.HORROR, keywords: ['wound','gore','dark','drip'],                 hasSkinTones: false },
  { id: 'hor_scream',   emoji: '😱', name: 'Face Screaming',      category: EmojiCategory.HORROR, keywords: ['horror','fear','shock','scared'],             hasSkinTones: false },
  { id: 'hor_house',    emoji: '🏚️', name: 'Haunted House',       category: EmojiCategory.HORROR, keywords: ['haunted','spooky','ruin','abandoned'],        hasSkinTones: false },
  { id: 'hor_knife',    emoji: '🔪', name: 'Kitchen Knife',       category: EmojiCategory.HORROR, keywords: ['slash','stab','horror','murder'],             hasSkinTones: false },
  { id: 'hor_chains',   emoji: '⛓️', name: 'Chains',             category: EmojiCategory.HORROR, keywords: ['trapped','bound','prisoner','shackle'],       hasSkinTones: false },
  { id: 'hor_moon',     emoji: '🌑', name: 'New Moon',            category: EmojiCategory.HORROR, keywords: ['dark','night','ominous','blackout'],          hasSkinTones: false },
  { id: 'hor_devil',    emoji: '😈', name: 'Smiling Devil',       category: EmojiCategory.HORROR, keywords: ['evil','demon','bad','horns'],                 hasSkinTones: false },
  { id: 'hor_bone',     emoji: '🦴', name: 'Bone',               category: EmojiCategory.HORROR, keywords: ['skeleton','dog','death','remains'],           hasSkinTones: false },
  { id: 'hor_brain',    emoji: '🧠', name: 'Brain',               category: EmojiCategory.HORROR, keywords: ['zombie','gore','think','organ'],              hasSkinTones: false },
  { id: 'hor_eye',      emoji: '👁️', name: 'Eye',               category: EmojiCategory.HORROR, keywords: ['stare','watching','creepy','all seeing'],     hasSkinTones: false },
  { id: 'hor_fog',      emoji: '🌫️', name: 'Fog',               category: EmojiCategory.HORROR, keywords: ['mist','mysterious','eerie','hide'],           hasSkinTones: false },
  { id: 'hor_pumpkin',  emoji: '🎃', name: 'Jack-o-Lantern',      category: EmojiCategory.HORROR, keywords: ['halloween','carve','spooky','october'],       hasSkinTones: false },
  { id: 'hor_virus',    emoji: '🦠', name: 'Microbe',             category: EmojiCategory.HORROR, keywords: ['germ','disease','contagion','bio'],           hasSkinTones: false },
  { id: 'hor_tornado',  emoji: '🌪️', name: 'Tornado',            category: EmojiCategory.HORROR, keywords: ['storm','swirl','destroy','chaos'],            hasSkinTones: false },
  { id: 'hor_axe',      emoji: '🪓', name: 'Axe',                category: EmojiCategory.HORROR, keywords: ['chop','horror','weapon','split'],             hasSkinTones: false },

  // Music
  { id: 'mus_note',     emoji: '🎵', name: 'Musical Note',        category: EmojiCategory.MUSIC, keywords: ['sound','music','melody','sing'],              hasSkinTones: false },
  { id: 'mus_notes',    emoji: '🎶', name: 'Musical Notes',       category: EmojiCategory.MUSIC, keywords: ['song','tune','harmony','play'],               hasSkinTones: false },
  { id: 'mus_guitar',   emoji: '🎸', name: 'Guitar',              category: EmojiCategory.MUSIC, keywords: ['rock','play','strum','electric'],             hasSkinTones: false },
  { id: 'mus_piano',    emoji: '🎹', name: 'Piano',               category: EmojiCategory.MUSIC, keywords: ['classical','keys','ivory','keyboard'],         hasSkinTones: false },
  { id: 'mus_trumpet',  emoji: '🎺', name: 'Trumpet',             category: EmojiCategory.MUSIC, keywords: ['jazz','brass','blow','horn'],                 hasSkinTones: false },
  { id: 'mus_violin',   emoji: '🎻', name: 'Violin',              category: EmojiCategory.MUSIC, keywords: ['classical','bow','string','orchestra'],        hasSkinTones: false },
  { id: 'mus_drum',     emoji: '🥁', name: 'Drum',               category: EmojiCategory.MUSIC, keywords: ['beat','rhythm','percussion','bang'],           hasSkinTones: false },
  { id: 'mus_conga',    emoji: '🪘', name: 'Long Drum',           category: EmojiCategory.MUSIC, keywords: ['latin','rhythm','beat','bongo'],              hasSkinTones: false },
  { id: 'mus_mic',      emoji: '🎤', name: 'Microphone',          category: EmojiCategory.MUSIC, keywords: ['sing','perform','karaoke','voice'],           hasSkinTones: false },
  { id: 'mus_phones',   emoji: '🎧', name: 'Headphones',          category: EmojiCategory.MUSIC, keywords: ['listen','audio','music','bass'],              hasSkinTones: false },
  { id: 'mus_score',    emoji: '🎼', name: 'Musical Score',       category: EmojiCategory.MUSIC, keywords: ['sheet','note','read','compose'],              hasSkinTones: false },
  { id: 'mus_cd',       emoji: '💿', name: 'CD',                  category: EmojiCategory.MUSIC, keywords: ['record','burn','album','disc'],               hasSkinTones: false },
  { id: 'mus_radio',    emoji: '📻', name: 'Radio',               category: EmojiCategory.MUSIC, keywords: ['broadcast','station','listen','fm'],          hasSkinTones: false },
  { id: 'mus_studio',   emoji: '🎙️', name: 'Studio Microphone',  category: EmojiCategory.MUSIC, keywords: ['record','podcast','voice','pro'],             hasSkinTones: false },
  { id: 'mus_sax',      emoji: '🎷', name: 'Saxophone',           category: EmojiCategory.MUSIC, keywords: ['jazz','blow','smooth','brass'],               hasSkinTones: false },
  { id: 'mus_accordion',emoji: '🪗', name: 'Accordion',           category: EmojiCategory.MUSIC, keywords: ['folk','squeeze','bellows','polka'],           hasSkinTones: false },
  { id: 'mus_banjo',    emoji: '🪕', name: 'Banjo',               category: EmojiCategory.MUSIC, keywords: ['country','pluck','folk','strings'],           hasSkinTones: false },
  { id: 'mus_fader',    emoji: '🎚️', name: 'Level Slider',       category: EmojiCategory.MUSIC, keywords: ['mix','audio','studio','eq'],                  hasSkinTones: false },
  { id: 'mus_knobs',    emoji: '🎛️', name: 'Control Knobs',      category: EmojiCategory.MUSIC, keywords: ['mix','dj','studio','dial'],                   hasSkinTones: false },
  { id: 'mus_speaker',  emoji: '🔊', name: 'Speaker',             category: EmojiCategory.MUSIC, keywords: ['loud','bass','blast','volume'],               hasSkinTones: false },
  { id: 'mus_disco',    emoji: '🪩', name: 'Mirror Ball',         category: EmojiCategory.MUSIC, keywords: ['dance','party','glitter','disco'],            hasSkinTones: false },
  { id: 'mus_theater',  emoji: '🎭', name: 'Performing Arts',     category: EmojiCategory.MUSIC, keywords: ['drama','act','stage','mask'],                 hasSkinTones: false },
  { id: 'mus_horn',     emoji: '📯', name: 'Postal Horn',         category: EmojiCategory.MUSIC, keywords: ['fanfare','blow','herald','hunt'],             hasSkinTones: false },
  { id: 'mus_film',     emoji: '🎬', name: 'Clapperboard',        category: EmojiCategory.MUSIC, keywords: ['film','movie','action','cut'],                hasSkinTones: false },
  { id: 'mus_venue',    emoji: '🎪', name: 'Circus Tent',         category: EmojiCategory.MUSIC, keywords: ['concert','venue','show','performance'],       hasSkinTones: false },

  // Ocean
  { id: 'sea_wave',     emoji: '🌊', name: 'Wave',                category: EmojiCategory.OCEAN, keywords: ['ocean','sea','surf','water'],                 hasSkinTones: false },
  { id: 'sea_beach',    emoji: '🏖️', name: 'Beach',              category: EmojiCategory.OCEAN, keywords: ['sand','sun','vacation','umbrella'],           hasSkinTones: false },
  { id: 'sea_shell',    emoji: '🐚', name: 'Spiral Shell',        category: EmojiCategory.OCEAN, keywords: ['seashell','beach','ocean','snail'],           hasSkinTones: false },
  { id: 'sea_crab',     emoji: '🦀', name: 'Crab',                category: EmojiCategory.OCEAN, keywords: ['seafood','pinch','crawl','red'],              hasSkinTones: false },
  { id: 'sea_lobster',  emoji: '🦞', name: 'Lobster',             category: EmojiCategory.OCEAN, keywords: ['seafood','red','claws','maine'],              hasSkinTones: false },
  { id: 'sea_shrimp',   emoji: '🦐', name: 'Shrimp',              category: EmojiCategory.OCEAN, keywords: ['seafood','prawn','pink','cocktail'],          hasSkinTones: false },
  { id: 'sea_octopus',  emoji: '🐙', name: 'Octopus',             category: EmojiCategory.OCEAN, keywords: ['tentacle','ink','smart','deep'],              hasSkinTones: false },
  { id: 'sea_squid',    emoji: '🦑', name: 'Squid',               category: EmojiCategory.OCEAN, keywords: ['tentacle','deep','calamari','sea'],           hasSkinTones: false },
  { id: 'sea_fish',     emoji: '🐟', name: 'Fish',                category: EmojiCategory.OCEAN, keywords: ['swim','aqua','scale','catch'],                hasSkinTones: false },
  { id: 'sea_tropical', emoji: '🐠', name: 'Tropical Fish',       category: EmojiCategory.OCEAN, keywords: ['colorful','reef','coral','nemo'],             hasSkinTones: false },
  { id: 'sea_puffer',   emoji: '🐡', name: 'Blowfish',            category: EmojiCategory.OCEAN, keywords: ['puff','poison','spiky','cute'],               hasSkinTones: false },
  { id: 'sea_shark',    emoji: '🦈', name: 'Shark',               category: EmojiCategory.OCEAN, keywords: ['bite','danger','fin','jaws'],                 hasSkinTones: false },
  { id: 'sea_whale',    emoji: '🐳', name: 'Spouting Whale',       category: EmojiCategory.OCEAN, keywords: ['big','blow','spout','sea'],                   hasSkinTones: false },
  { id: 'sea_dolphin',  emoji: '🐬', name: 'Dolphin',             category: EmojiCategory.OCEAN, keywords: ['smart','jump','cute','flipper'],              hasSkinTones: false },
  { id: 'sea_sail',     emoji: '⛵', name: 'Sailboat',            category: EmojiCategory.OCEAN, keywords: ['sail','wind','sea','boat'],                   hasSkinTones: false },
  { id: 'sea_surf',     emoji: '🏄', name: 'Person Surfing',       category: EmojiCategory.OCEAN, keywords: ['surf','wave','beach','ride'],                 hasSkinTones: true, skinToneVariants: applySkinTones('🏄') },
  { id: 'sea_dive',     emoji: '🤿', name: 'Diving Mask',         category: EmojiCategory.OCEAN, keywords: ['snorkel','dive','underwater','scuba'],        hasSkinTones: false },
  { id: 'sea_island',   emoji: '🏝️', name: 'Desert Island',      category: EmojiCategory.OCEAN, keywords: ['tropical','palm','alone','paradise'],         hasSkinTones: false },
  { id: 'sea_anchor',   emoji: '⚓', name: 'Anchor',              category: EmojiCategory.OCEAN, keywords: ['ship','port','sailor','dock'],                hasSkinTones: false },
  { id: 'sea_coral',    emoji: '🪸', name: 'Coral',               category: EmojiCategory.OCEAN, keywords: ['reef','colorful','marine','ocean'],           hasSkinTones: false },
  { id: 'sea_seal',     emoji: '🦭', name: 'Seal',                category: EmojiCategory.OCEAN, keywords: ['flipper','marine','cute','bark'],             hasSkinTones: false },
  { id: 'sea_palm',     emoji: '🌴', name: 'Palm Tree',            category: EmojiCategory.OCEAN, keywords: ['beach','tropical','coconut','holiday'],       hasSkinTones: false },
  { id: 'sea_mermaid',  emoji: '🧜', name: 'Merperson',           category: EmojiCategory.OCEAN, keywords: ['mermaid','myth','tail','swim'],               hasSkinTones: true, skinToneVariants: applySkinTones('🧜') },
  { id: 'sea_flamingo', emoji: '🦩', name: 'Flamingo',            category: EmojiCategory.OCEAN, keywords: ['pink','wade','elegant','bird'],               hasSkinTones: false },
  { id: 'sea_whale2',   emoji: '🐋', name: 'Whale',               category: EmojiCategory.OCEAN, keywords: ['mammal','large','blue','ocean'],              hasSkinTones: false },
];

export const emojiDatabase = new Map<string, Emoji>();

emojis.forEach(emoji => {
  emojiDatabase.set(emoji.id, emoji);
});

export const getEmojisByCategory = (category: EmojiCategory): Emoji[] => {
  return emojis.filter(emoji => emoji.category === category);
};

export const searchEmojis = (query: string): Emoji[] => {
  const lowerQuery = query.toLowerCase();
  return emojis.filter(emoji =>
    emoji.name.toLowerCase().includes(lowerQuery) ||
    emoji.keywords.some(keyword => keyword.toLowerCase().includes(lowerQuery))
  );
};

export const getAllCategories = (): EmojiCategory[] => {
  return Object.values(EmojiCategory).filter(cat => cat !== EmojiCategory.RECENT);
};

export default emojis;
